# Janua API - Enclii CLI Service Specification
# This format matches the CLI parser expectations (enclii.dev/v1alpha)
apiVersion: enclii.dev/v1alpha
kind: Service
metadata:
  name: janua-api
  project: janua
spec:
  build:
    type: dockerfile
    dockerfile: apps/api/Dockerfile
  runtime:
    port: 4100
    replicas: 2
    healthCheck: /health
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "4100"
