version: "2"

run:
  timeout: 5m
  go: "1.24"
  tests: false  # Skip linting test files (many false positives)

linters:
  default: none
  enable:
    - govet
    - errcheck       # Catch unchecked error returns (critical for reliability)
    - staticcheck    # Advanced static analysis including nil checks (SA rules)
    - ineffassign    # Catch useless variable assignments
    # - unused        # TODO: Re-enable after removing unused code

formatters:
  enable:
    - gofmt

issues:
  # Exclude staticcheck style suggestions (QF* rules) - these are suggestions, not errors
  exclude-rules:
    - linters:
        - staticcheck
      text: "^QF"

  # Limit issues to avoid overwhelming output - will still catch new problems
  max-issues-per-linter: 20
  max-same-issues: 5
