# LinkStack Service Specification for SuLuna
# Self-hosted Linktree alternative for client deployment
#
# Repository: https://github.com/LinkStackOrg/linkstack-docker
# License: AGPL-3.0
#
# Agency Model: Deployed in client namespace, managed by MADFAM
# Client: SuLuna (suluna.mx@gmail.com)
# Domain: links.suluna.mx

apiVersion: enclii.io/v1
kind: Service
metadata:
  name: linkstack
  namespace: suluna-production  # Client-scoped namespace
  labels:
    app: linkstack
    tier: client-application
    client: suluna
    criticality: medium
  annotations:
    enclii.dev/description: "LinkStack - Self-hosted link sharing for SuLuna"
    enclii.dev/owner: managed-services
    enclii.dev/client: suluna
    enclii.dev/billing: suluna-org

spec:
  # ==========================================================================
  # SOURCE CONFIGURATION
  # ==========================================================================
  source:
    # Use official LinkStack Docker image
    image:
      repository: linkstackorg/linkstack
      tag: latest
      pullPolicy: Always

  # ==========================================================================
  # DEPLOYMENT CONFIGURATION
  # ==========================================================================
  deployment:
    replicas: 1  # Single replica for cost efficiency

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0

    # Container configuration
    container:
      port: 80

      # Health checks
      healthCheck:
        path: /
        port: 80
        initialDelaySeconds: 30
        periodSeconds: 15
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1

      # Readiness check
      readinessCheck:
        path: /
        port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 2

      # Resource limits (PHP/Laravel is memory-hungry)
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

      # Security context
      securityContext:
        runAsNonRoot: false  # LinkStack needs root for Apache
        readOnlyRootFilesystem: false  # Needs write for SQLite
        allowPrivilegeEscalation: false

    # Pod configuration
    pod:
      labels:
        app: linkstack
        client: suluna

  # ==========================================================================
  # NETWORKING
  # ==========================================================================
  networking:
    # Client domain
    domains:
      - name: links.suluna.mx
        primary: true
        tls:
          enabled: true
          provider: cloudflare

    # Internal service
    service:
      type: ClusterIP
      port: 80
      targetPort: 80

    # Ingress rules
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "20m"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header X-XSS-Protection "1; mode=block" always;

      # Rate limiting
      rateLimit:
        enabled: true
        requestsPerMinute: 120
        burst: 30

  # ==========================================================================
  # ENVIRONMENT CONFIGURATION
  # ==========================================================================
  env:
    # Application settings
    - name: SERVER_ADMIN
      value: "admin@madfam.io"

    # LinkStack specific
    - name: HTTP_SERVER_NAME
      value: "links.suluna.mx"

    - name: HTTPS_SERVER_NAME
      value: "links.suluna.mx"

    - name: LOG_CHANNEL
      value: "stderr"

    - name: TZ
      value: "America/Mexico_City"

    # PHP tuning
    - name: PHP_MEMORY_LIMIT
      value: "256M"

    - name: UPLOAD_MAX_FILESIZE
      value: "20M"

  # ==========================================================================
  # PERSISTENT STORAGE
  # ==========================================================================
  volumes:
    # SQLite database + user uploads
    - name: linkstack-data
      mountPath: /htdocs
      persistentVolumeClaim:
        storageClass: longhorn  # Enclii's default storage
        accessMode: ReadWriteOnce
        size: 5Gi
        labels:
          client: suluna
          backup: enabled

  # ==========================================================================
  # DEPLOYMENT PIPELINE
  # ==========================================================================
  pipeline:
    # Manual deployment (not auto-deploy from git)
    autoDeploy: false

    stages:
      - name: deploy
        strategy: rolling
        rollbackOnFailure: true

    webhooks:
      onSuccess:
        - url: "${SLACK_WEBHOOK_URL}"
          payload: |
            {
              "text": "✅ LinkStack deployed for SuLuna",
              "attachments": [{
                "color": "good",
                "fields": [
                  {"title": "Client", "value": "SuLuna", "short": true},
                  {"title": "Domain", "value": "links.suluna.mx", "short": true}
                ]
              }]
            }

  # ==========================================================================
  # MONITORING
  # ==========================================================================
  monitoring:
    # Basic uptime monitoring
    healthEndpoint:
      enabled: true
      path: /
      interval: 60

    alerts:
      - name: LinkStackSuLunaDown
        condition: up{service="linkstack",namespace="suluna-production"} == 0
        duration: 5m
        severity: warning
        annotations:
          summary: "SuLuna LinkStack is down"
          description: "LinkStack instance for SuLuna has been unavailable for 5 minutes"

  # ==========================================================================
  # BACKUP CONFIGURATION
  # ==========================================================================
  backup:
    enabled: true
    schedule: "0 3 * * *"  # Daily at 3 AM
    retention: 7  # Keep 7 days of backups
    destination:
      type: r2
      bucket: suluna-backups
      path: linkstack/

  # ==========================================================================
  # CLIENT ISOLATION
  # ==========================================================================
  isolation:
    # Network policies - only allow traffic from Cloudflare Tunnel
    networkPolicy:
      enabled: true
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  name: cloudflare-tunnel
          ports:
            - port: 80
              protocol: TCP

    # Resource quotas for the namespace
    resourceQuota:
      enabled: true
      limits:
        cpu: "2"
        memory: "2Gi"
        persistentVolumeClaims: "3"
        services: "5"
