# ============================================================================
# SuLuna LinkStack - Raw Kubernetes Manifest
# ============================================================================
# Agency Model Validation Deployment
# Client: SuLuna (suluna.mx@gmail.com)
# Managed By: MADFAM (admin@madfam.io)
#
# Deploy: kubectl apply -f suluna-linkstack.k8s.yaml
# ============================================================================

---
# ============================================================================
# PersistentVolumeClaim - LinkStack Data Storage
# ============================================================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkstack-data
  namespace: suluna-production
  labels:
    app: linkstack
    client: suluna
    managed-by: madfam
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

---
# ============================================================================
# ConfigMap - LinkStack Environment Configuration
# ============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkstack-config
  namespace: suluna-production
  labels:
    app: linkstack
    client: suluna
    managed-by: madfam
data:
  # Server Configuration
  SERVER_ADMIN: "admin@madfam.io"
  HTTP_SERVER_NAME: "links.suluna.mx"
  HTTPS_SERVER_NAME: "links.suluna.mx"

  # Application Settings
  LOG_LEVEL: "info"
  TIMEZONE: "America/Mexico_City"
  PHP_MEMORY_LIMIT: "256M"
  UPLOAD_MAX_FILESIZE: "16M"

  # Security - TLS handled by Cloudflare Tunnel
  FORCE_HTTPS: "true"

  # Database - SQLite (embedded, uses PVC)
  DB_CONNECTION: "sqlite"

---
# ============================================================================
# Secret - Sensitive Configuration (Template)
# ============================================================================
# NOTE: In production, use external-secrets or sealed-secrets
# This is a template - actual secret should be created separately
apiVersion: v1
kind: Secret
metadata:
  name: linkstack-secrets
  namespace: suluna-production
  labels:
    app: linkstack
    client: suluna
    managed-by: madfam
type: Opaque
stringData:
  # Application Key - Generate with: openssl rand -base64 32
  APP_KEY: "base64:REPLACE_WITH_GENERATED_KEY"

  # Optional: If using external database
  # DB_PASSWORD: ""

---
# ============================================================================
# Deployment - LinkStack Application
# ============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkstack
  namespace: suluna-production
  labels:
    app: linkstack
    client: suluna
    managed-by: madfam
  annotations:
    description: "Self-hosted link aggregator for SuLuna"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: linkstack
      client: suluna
  template:
    metadata:
      labels:
        app: linkstack
        client: suluna
        managed-by: madfam
    spec:
      # Security Context
      securityContext:
        fsGroup: 33  # www-data group

      containers:
        - name: linkstack
          image: linkstackorg/linkstack:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP

          # Environment from ConfigMap
          envFrom:
            - configMapRef:
                name: linkstack-config
            - secretRef:
                name: linkstack-secrets

          # Resource Limits
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          # Volume Mounts
          volumeMounts:
            - name: linkstack-data
              mountPath: /htdocs

          # Health Checks
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3

          # Startup Probe (for slow container starts)
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 30  # 150 seconds max startup

      # Volumes
      volumes:
        - name: linkstack-data
          persistentVolumeClaim:
            claimName: linkstack-data

      # Scheduling
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
# ============================================================================
# Service - Internal ClusterIP for Cloudflare Tunnel Ingress
# ============================================================================
apiVersion: v1
kind: Service
metadata:
  name: linkstack
  namespace: suluna-production
  labels:
    app: linkstack
    client: suluna
    managed-by: madfam
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: linkstack
    client: suluna

---
# ============================================================================
# NetworkPolicy - Restrict Traffic (Defense in Depth)
# ============================================================================
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: linkstack-network-policy
  namespace: suluna-production
  labels:
    app: linkstack
    client: suluna
    managed-by: madfam
spec:
  podSelector:
    matchLabels:
      app: linkstack
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow traffic from cloudflared in foundry namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: foundry
          podSelector:
            matchLabels:
              app: cloudflared
      ports:
        - protocol: TCP
          port: 80
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTPS for external API calls (optional)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
      ports:
        - protocol: TCP
          port: 443

---
# ============================================================================
# PodDisruptionBudget - Maintain Availability During Updates
# ============================================================================
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: linkstack-pdb
  namespace: suluna-production
  labels:
    app: linkstack
    client: suluna
    managed-by: madfam
spec:
  minAvailable: 0  # Single replica, allow disruption during maintenance
  selector:
    matchLabels:
      app: linkstack
      client: suluna
