---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: switchyard-api
spec:
  template:
    spec:
      containers:
      - name: switchyard-api
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: ENCLII_LOG_LEVEL
          value: "info"
        - name: ENCLII_RATE_LIMIT_REQUESTS_PER_MINUTE
          value: "5000"
        - name: ENCLII_DB_POOL_SIZE
          value: "20"
        - name: ENCLII_CACHE_TTL_SECONDS
          value: "3600"