# Aureo Labs Business Website - Enclii Service Specification
# Enterprise website for Aureo Labs (a MADFAM Company)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: aureo-labs
  project: aureo-labs
  labels:
    app: aureo-labs
    component: web
    tier: production
    team: aureo-labs

spec:
  build:
    source:
      repo: github.com/madfam-io/aureo-labs
      branch: main
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"
      NEXT_TELEMETRY_DISABLED: "1"

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  networking:
    port: 3000
    domains:
      - aureo.labs
      - www.aureo.labs
      - aureo-labs.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    NEXT_TELEMETRY_DISABLED: "1"

  deployment:
    strategy: rolling
    maxSurge: 1
    maxUnavailable: 0
