# Auto-Claude Redis - Coordination Layer
# Provides task queues, distributed locks, and agent state management

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: auto-claude-redis
  project: enclii  # Using existing project (madfam-automation API broken)
  description: Redis coordination layer for Auto-Claude agent orchestration

spec:
  build:
    type: image
    image: redis:7-alpine

  runtime:
    port: 6379
    replicas: 1
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"

    # Redis health check
    healthCheck:
      command: ["redis-cli", "ping"]
      initialDelaySeconds: 5
      periodSeconds: 10

    # Redis configuration
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --maxmemory
      - "768mb"
      - --maxmemory-policy
      - allkeys-lru
      - --tcp-backlog
      - "511"
      - --timeout
      - "300"
      - --tcp-keepalive
      - "60"

  env:
    - name: REDIS_PASSWORD
      valueFrom:
        secretKeyRef:
          name: auto-claude-secrets
          key: redis-password

  volumes:
    - name: redis-data
      mountPath: /data
      size: 10Gi
      storageClassName: hetzner-ssd
      accessMode: ReadWriteOnce

  # Internal service only (no external domain)
  domains: []

  # No autoscaling for Redis (single instance with persistence)
  autoscaling:
    enabled: false

  monitoring:
    prometheus:
      enabled: true
      port: 9121
      exporter: redis

  slo:
    availability: 99.9
    latencyP95: 10  # Redis should respond in <10ms
    errorRate: 0.5
