# Auto-Claude Agent - Autonomous Coding Agents
# Deploys UPSTREAM repository with Janua SSO sidecar (no fork needed!)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: auto-claude-agent
  project: enclii  # Using existing project (madfam-automation API broken)
  description: Autonomous Claude Code agents with Janua SSO authentication

spec:
  build:
    type: dockerfile
    dockerfile: Dockerfile  # Auto-Claude's existing Dockerfile
    context: .
    source:
      git:
        repository: https://github.com/AndyMik90/Auto-Claude  # ← UPSTREAM!
        branch: main
        autoDeploy: false  # Manual deploys only for stability

  # Sidecar: Janua Auth Proxy
  sidecars:
    - name: auth-proxy
      image: ghcr.io/madfam-org/janua-auth-proxy:latest
      port: 8081
      env:
        - name: UPSTREAM_SERVICE
          value: http://localhost:8080  # Auto-Claude's port
        - name: JANUA_URL
          value: https://auth.madfam.io
        - name: REQUIRED_SCOPES
          value: agent:control  # Only users with agent:control can access
        - name: PUBLIC_PATHS
          value: /health,/metrics
        - name: LOG_LEVEL
          value: info

  # Main Auto-Claude container
  runtime:
    port: 8080  # Internal only, not exposed directly
    replicas: 1  # KEDA will manage scaling
    resources:
      requests:
        cpu: "2000m"
        memory: "2Gi"
      limits:
        cpu: "4000m"
        memory: "4Gi"

    healthCheck: /health
    readinessProbe:
      path: /health
      initialDelaySeconds: 60
      periodSeconds: 10
    livenessProbe:
      path: /health
      initialDelaySeconds: 120
      periodSeconds: 30

  # Auto-Claude environment variables
  env:
    - name: PORT
      value: "8080"
    - name: NODE_ENV
      value: production

    # Workspace configuration
    - name: WORKSPACE_ROOT
      value: /workspace
    - name: GIT_CACHE_DIR
      value: /workspace/repos/.git-cache
    - name: SESSION_DIR
      value: /workspace/sessions
    - name: MAX_CONCURRENT_TASKS
      value: "3"
    - name: TASK_TIMEOUT_SECONDS
      value: "3600"

    # Redis coordination
    - name: REDIS_URL
      value: redis://auto-claude-redis.madfam-automation.svc.cluster.local:6379

    # Claude API credentials
    - name: ANTHROPIC_API_KEY
      valueFrom:
        secretKeyRef:
          name: auto-claude-secrets
          key: anthropic-api-key

    # GitHub access for 19 repositories
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: auto-claude-secrets
          key: github-token

    # Janua SSO integration (for creating users, checking permissions)
    - name: JANUA_URL
      value: https://auth.madfam.io
    - name: JANUA_CLIENT_ID
      value: jnc_lSGMbQtCGdHSctd4mEQoaklLBCv7xXhe
    - name: JANUA_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: auto-claude-secrets
          key: janua-client-secret

  # Persistent storage for git cache and worktrees
  volumes:
    - name: repo-cache
      mountPath: /workspace/repos
      persistentVolumeClaim: auto-claude-repo-cache  # From k8s/auto-claude-storage.yaml

    - name: session-data
      mountPath: /workspace/sessions
      size: 20Gi
      storageClassName: hetzner-ssd
      accessMode: ReadWriteMany

  # Expose auth proxy (port 8081), NOT main container
  domains:
    - domain: agents-api.madfam.io
      targetPort: 8081  # Routes to Janua auth proxy
      tls: true
      tlsIssuer: cloudflare

  # KEDA autoscaling (queue-based)
  autoscaling:
    enabled: true
    type: keda
    minReplicas: 1
    maxReplicas: 8
    cooldownPeriod: 300
    triggers:
      - type: redis
        metadata:
          address: auto-claude-redis.madfam-automation.svc.cluster.local:6379
          listName: autoclaudeQueue:pending
          listLength: "3"  # 1 agent per 3 tasks
          activationListLength: "1"
      - type: cpu
        metadata:
          type: Utilization
          value: "70"

  # Prometheus metrics
  monitoring:
    prometheus:
      enabled: true
      port: 9090
      path: /metrics

  slo:
    availability: 99.5
    latencyP95: 5000  # 5s for API responses
    errorRate: 2.0
