# Avala - Enclii Service Specification
# Algorithmic trading platform with backtesting and live execution

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: avala-api
  project: madfam-platform
  labels:
    app: avala
    component: api
    tier: production
    team: madfam

spec:
  build:
    source:
      repo: github.com/madfam-io/avala
      branch: main
      path: .
    builder: dockerfile
    dockerfile: Dockerfile

  runtime:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 4000m
        memory: 4Gi
    replicas:
      min: 3
      max: 10
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 70
        - type: memory
          target: 75
    healthCheck:
      liveness:
        path: /api/health
        port: 3000
        initialDelaySeconds: 30
      readiness:
        path: /api/health
        port: 3000
        initialDelaySeconds: 15

  routes:
    - host: avala.madfam.io
      path: /
      port: 3000

  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "3000"

  secrets:
    - name: DATABASE_URL
      key: avala-db-url
    - name: REDIS_URL
      key: avala-redis-url
    - name: ALPACA_API_KEY
      key: avala-alpaca-key
    - name: ALPACA_SECRET_KEY
      key: avala-alpaca-secret

  deployment:
    strategy: canary
    canary:
      steps:
        - weight: 10
          pause: 5m
        - weight: 50
          pause: 10m
        - weight: 100
      analysis:
        metrics:
          - name: error-rate
            threshold: 1
          - name: latency-p99
            threshold: 500

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: avala-worker
  project: madfam-platform
  labels:
    app: avala
    component: worker
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-io/avala
      branch: main
      path: .
    builder: dockerfile
    dockerfile: Dockerfile.worker

  runtime:
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 8Gi
    replicas:
      min: 2
      max: 8
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 60

  env:
    - name: NODE_ENV
      value: production
    - name: WORKER_MODE
      value: "true"

  secrets:
    - name: DATABASE_URL
      key: avala-db-url
    - name: REDIS_URL
      key: avala-redis-url
    - name: ALPACA_API_KEY
      key: avala-alpaca-key
    - name: ALPACA_SECRET_KEY
      key: avala-alpaca-secret
