# Bloom Scroll - Enclii Service Specification
# Perspective-driven content aggregator (anti-doomscroll)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: bloom-scroll-api
  project: madfam-platform
  labels:
    app: bloom-scroll
    component: api
    tier: production
    team: madfam

spec:
  build:
    source:
      repo: github.com/madfam-io/bloom-scroll
      branch: main
      path: backend
    builder: dockerfile
    dockerfile: Dockerfile
    buildEnv:
      PYTHON_VERSION: "3.11"

  runtime:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi  # Sentence-BERT embeddings need memory
    replicas:
      min: 2
      max: 6
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 70
        - type: memory
          target: 75
    healthCheck:
      liveness:
        path: /health
        port: 8000
        initialDelaySeconds: 30
      readiness:
        path: /health
        port: 8000
        initialDelaySeconds: 15

  routes:
    - host: api.bloomscroll.app
      path: /
      port: 8000

  env:
    - name: ENVIRONMENT
      value: production
    - name: PORT
      value: "8000"
    - name: EMBEDDING_MODEL
      value: all-MiniLM-L6-v2

  secrets:
    - name: DATABASE_URL
      key: bloom-scroll-db-url
    - name: REDIS_URL
      key: bloom-scroll-redis-url

  deployment:
    strategy: canary
    canary:
      steps:
        - weight: 20
          pause: 5m
        - weight: 100
      analysis:
        metrics:
          - name: error-rate
            threshold: 2

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: bloom-scroll-web
  project: madfam-platform
  labels:
    app: bloom-scroll
    component: web
    tier: production
  annotations:
    description: "Flutter web frontend for Bloom Scroll"

spec:
  build:
    source:
      repo: github.com/madfam-io/bloom-scroll
      branch: main
      path: frontend
    builder: dockerfile
    dockerfile: Dockerfile

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    replicas:
      min: 2
      max: 4
    healthCheck:
      liveness:
        path: /
        port: 80
      readiness:
        path: /
        port: 80

  routes:
    - host: bloomscroll.app
      path: /
      port: 80
    - host: www.bloomscroll.app
      path: /
      port: 80

  env:
    - name: API_URL
      value: https://api.bloomscroll.app
