# Blueprint Harvester - Enclii Service Specification
# 3D-printable file discovery, harvesting, and management engine

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: blueprint-harvester-api
  project: aureo-labs
  labels:
    app: blueprint-harvester
    component: api
    tier: production
    team: aureo-labs

spec:
  build:
    source:
      repo: github.com/madfam-io/blueprint-harvester
      branch: main
      path: services
    builder: dockerfile
    dockerfile: Dockerfile.api
    buildEnv:
      PYTHON_VERSION: "3.11"

  runtime:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    replicas:
      min: 2
      max: 8
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 70
    healthCheck:
      liveness:
        path: /health
        port: 8000
      readiness:
        path: /health/ready
        port: 8000

  routes:
    - host: api.blueprint-harvester.io
      path: /
      port: 8000

  env:
    - name: ENVIRONMENT
      value: production

  secrets:
    - name: DATABASE_URL
      key: blueprint-db-url
    - name: REDIS_URL
      key: blueprint-redis-url
    - name: S3_ENDPOINT
      key: blueprint-s3-endpoint
    - name: S3_ACCESS_KEY
      key: blueprint-s3-access-key
    - name: S3_SECRET_KEY
      key: blueprint-s3-secret-key
    - name: OPENSEARCH_URL
      key: blueprint-opensearch-url

  deployment:
    strategy: rolling
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: blueprint-harvester-worker
  project: aureo-labs
  labels:
    app: blueprint-harvester
    component: worker
    tier: production
  annotations:
    description: "Geometry processing and ML pipeline worker"

spec:
  build:
    source:
      repo: github.com/madfam-io/blueprint-harvester
      branch: main
      path: services
    builder: dockerfile
    dockerfile: Dockerfile.processing
    buildEnv:
      PYTHON_VERSION: "3.11"

  runtime:
    resources:
      requests:
        cpu: 1000m
        memory: 4Gi
      limits:
        cpu: 4000m
        memory: 16Gi # Large meshes and ML models
    replicas:
      min: 2
      max: 10
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 60
        - type: memory
          target: 70

  env:
    - name: WORKER_TYPE
      value: processor
    - name: CONCURRENCY
      value: "4"

  secrets:
    - name: DATABASE_URL
      key: blueprint-db-url
    - name: REDIS_URL
      key: blueprint-redis-url
    - name: S3_ENDPOINT
      key: blueprint-s3-endpoint
    - name: S3_ACCESS_KEY
      key: blueprint-s3-access-key
    - name: S3_SECRET_KEY
      key: blueprint-s3-secret-key
    - name: KAFKA_BROKERS
      key: blueprint-kafka-brokers

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: blueprint-harvester-web
  project: aureo-labs
  labels:
    app: blueprint-harvester
    component: web
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-io/blueprint-harvester
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"

  runtime:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 512Mi
    replicas:
      min: 2
      max: 4
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  routes:
    - host: blueprint-harvester.io
      path: /
      port: 3000
    - host: www.blueprint-harvester.io
      path: /
      port: 3000

  env:
    - name: NODE_ENV
      value: production
    - name: NEXT_PUBLIC_API_URL
      value: https://api.blueprint-harvester.io
