# ClaudeCodeUI - Web Interface for Auto-Claude Agents
# Forked from siteboon/claudecodeui with Janua SSO integration

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: claude-ui
  project: enclii  # Using existing project (madfam-automation API broken)
  description: Web and mobile UI for managing Auto-Claude agent sessions

spec:
  build:
    type: dockerfile
    dockerfile: Dockerfile
    context: .
    source:
      git:
        repository: https://github.com/madfam-org/claudecodeui  # ← Fork with Janua integration
        branch: main
        autoDeploy: true

  runtime:
    port: 3001
    replicas: 2
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

    healthCheck: /api/health
    readinessProbe:
      path: /api/health
      initialDelaySeconds: 15
      periodSeconds: 5
    livenessProbe:
      path: /api/health
      initialDelaySeconds: 30
      periodSeconds: 10

  env:
    - name: PORT
      value: "3001"
    - name: NODE_ENV
      value: production
    - name: HOSTNAME
      value: "0.0.0.0"

    # Public URLs
    - name: NEXT_PUBLIC_APP_URL
      value: https://agents.madfam.io
    - name: NEXT_PUBLIC_API_URL
      value: https://agents-api.madfam.io
    - name: NEXT_PUBLIC_WS_URL
      value: wss://agents.madfam.io

    # Janua SSO integration
    - name: NEXT_PUBLIC_JANUA_URL
      value: https://auth.madfam.io
    - name: NEXT_PUBLIC_JANUA_CLIENT_ID
      value: jnc_lSGMbQtCGdHSctd4mEQoaklLBCv7xXhe
    - name: JANUA_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: auto-claude-secrets
          key: janua-client-secret

    # Redis for session management
    - name: REDIS_URL
      value: redis://auto-claude-redis.madfam-automation.svc.cluster.local:6379

    # Kubernetes API access (for agent discovery)
    - name: KUBERNETES_NAMESPACE
      value: madfam-automation
    - name: IN_CLUSTER
      value: "true"

    # Auto-Claude Agent API
    - name: AGENT_API_URL
      value: http://auto-claude-agent.madfam-automation.svc.cluster.local:8080

    # MADFAM branding
    - name: NEXT_PUBLIC_BRAND_NAME
      value: "MADFAM Autochess"
    - name: NEXT_PUBLIC_BRAND_LOGO
      value: "https://madfam.io/logo.svg"
    - name: NEXT_PUBLIC_SUPPORT_EMAIL
      value: "support@madfam.io"

    # Analytics (optional)
    - name: NEXT_PUBLIC_ANALYTICS_URL
      value: https://analytics.madfam.io
    - name: NEXT_PUBLIC_ANALYTICS_SITE_ID
      value: auto-claude-ui

  domains:
    - domain: agents.madfam.io
      tls: true
      tlsIssuer: cloudflare

  # HPA autoscaling (load-based)
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  slo:
    availability: 99.9
    latencyP95: 500  # 500ms for UI responses
    errorRate: 1.0
