# Coforma Studio - Enclii Dogfooding Service Specification
# Customer Advisory Board SaaS Platform

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: coforma-studio
  project: aureo-labs
  labels:
    app: coforma-studio
    component: full-stack
    tier: production
    team: aureo-labs

spec:
  services:
    # NestJS API
    - name: coforma-api
      build:
        source:
          repo: github.com/madfam-io/coforma-studio
          branch: main
          path: apps/api
        builder: dockerfile
        buildEnv:
          NODE_VERSION: "20"

      runtime:
        port: 5101
        replicas: 2
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi

        healthCheck:
          path: /api/health
          interval: 30s
          timeout: 10s
          retries: 3

        readinessProbe:
          path: /api/health
          initialDelaySeconds: 15
          periodSeconds: 10

        livenessProbe:
          path: /api/health
          initialDelaySeconds: 30
          periodSeconds: 15

      env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "5101"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: redis-url
        - name: MEILISEARCH_HOST
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: meilisearch-host
        - name: MEILISEARCH_KEY
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: meilisearch-key
        - name: JANUA_ISSUER_URL
          value: https://auth.enclii.io
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: stripe-webhook-secret

      routes:
        - host: api.coforma.studio
          path: /
          tls:
            enabled: true
            provider: cloudflare

    # Next.js Web Frontend
    - name: coforma-web
      build:
        source:
          repo: github.com/madfam-io/coforma-studio
          branch: main
          path: apps/web
        builder: dockerfile
        buildEnv:
          NODE_VERSION: "20"

      runtime:
        port: 3000
        replicas: 2
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

        healthCheck:
          path: /api/health
          interval: 30s
          timeout: 5s

      env:
        - name: NODE_ENV
          value: production
        - name: NEXT_PUBLIC_API_URL
          value: https://api.coforma.studio
        - name: NEXT_PUBLIC_JANUA_URL
          value: https://auth.enclii.io
        - name: NEXTAUTH_URL
          value: https://coforma.studio
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: nextauth-secret

      routes:
        - host: coforma.studio
          path: /
          tls:
            enabled: true
            provider: cloudflare
        - host: www.coforma.studio
          path: /
          tls:
            enabled: true
          redirect: coforma.studio

  # Background job worker
  workers:
    - name: coforma-worker
      build:
        source:
          repo: github.com/madfam-io/coforma-studio
          branch: main
          path: apps/api
        builder: dockerfile

      runtime:
        replicas: 1
        command: ["node", "dist/worker.js"]
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

      env:
        - name: NODE_ENV
          value: production
        - name: WORKER_MODE
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: coforma-secrets
              key: redis-url

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    metrics:
      - type: cpu
        averageUtilization: 70
      - type: memory
        averageUtilization: 80

  networkPolicy:
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                name: enclii-platform
        ports:
          - port: 5101
          - port: 3000
    egress:
      - to:
          - namespaceSelector:
              matchLabels:
                name: databases
        ports:
          - port: 5432
          - port: 6379
          - port: 7700

  monitoring:
    prometheus:
      enabled: true
      path: /metrics
      port: 5101
    alerts:
      - name: coforma-high-error-rate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
        for: 5m
        severity: critical
      - name: coforma-high-latency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 10m
        severity: warning
