# Cotiza Studio (digifab-quoting) - Enclii Service Specification
# Multi-tenant quoting platform for digital fabrication

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: cotiza-api
  project: aureo-labs
  labels:
    app: cotiza-studio
    component: api
    tier: production
    team: aureo-labs

spec:
  build:
    source:
      repo: github.com/madfam-org/digifab-quoting
      branch: main
      path: apps/api
    builder: dockerfile
    buildEnv:
      NODE_VERSION: "20"

  runtime:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    replicas:
      min: 2
      max: 10
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 70
    healthCheck:
      liveness:
        path: /health
        port: 3001
      readiness:
        path: /health
        port: 3001

  networking:
    port: 3001
    domains:
      - api.cotiza.studio
      - cotiza-api.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    PORT: "3001"

  secrets:
    - name: DATABASE_URL
      key: cotiza/database-url
    - name: JWT_SECRET
      key: cotiza/jwt-secret
    - name: STRIPE_SECRET_KEY
      key: cotiza/stripe-secret
    - name: AWS_ACCESS_KEY_ID
      key: shared/r2-access-key
    - name: AWS_SECRET_ACCESS_KEY
      key: shared/r2-secret-key

  database:
    type: postgresql
    provider: shared
    name: cotiza_production
    migrations:
      enabled: true
      command: "npx prisma migrate deploy"

  deployment:
    strategy: canary
    canary:
      steps:
        - weight: 10
          pause: 2m
        - weight: 50
          pause: 5m
        - weight: 100
      rollback:
        automatic: true
        errorThreshold: 2

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: cotiza-web
  project: aureo-labs
  labels:
    app: cotiza-studio
    component: web
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-org/digifab-quoting
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"
      NEXT_PUBLIC_API_URL: https://api.cotiza.studio

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  networking:
    port: 3000
    domains:
      - cotiza.studio
      - www.cotiza.studio
      - cotiza.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    NEXT_PUBLIC_API_URL: https://api.cotiza.studio

  deployment:
    strategy: rolling
