# Dhanam - Enclii Service Specification
# Budget & Wealth Tracking Platform with ESG crypto insights

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: dhanam-api
  project: aureo-labs
  labels:
    app: dhanam
    component: api
    tier: production
    team: aureo-labs

spec:
  build:
    source:
      repo: github.com/madfam-org/dhanam
      branch: main
      path: apps/api
    builder: dockerfile
    buildEnv:
      NODE_VERSION: "20"

  runtime:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    replicas:
      min: 2
      max: 10
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 70
    healthCheck:
      liveness:
        path: /health
        port: 3001
      readiness:
        path: /health
        port: 3001

  networking:
    port: 3001
    domains:
      - api.dhanam.app
      - dhanam-api.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    PORT: "3001"

  secrets:
    - name: DATABASE_URL
      key: dhanam/database-url
    - name: JWT_SECRET
      key: dhanam/jwt-secret
    - name: BELVO_SECRET_ID
      key: dhanam/belvo-secret-id
    - name: BELVO_SECRET_PASSWORD
      key: dhanam/belvo-secret-password
    - name: PLAID_CLIENT_ID
      key: dhanam/plaid-client-id
    - name: PLAID_SECRET
      key: dhanam/plaid-secret
    - name: BITSO_API_KEY
      key: dhanam/bitso-api-key
    - name: BITSO_API_SECRET
      key: dhanam/bitso-api-secret

  database:
    type: postgresql
    provider: shared
    name: dhanam_production
    migrations:
      enabled: true
      command: "npx prisma migrate deploy"

  cache:
    type: redis
    provider: shared
    db: 3

  deployment:
    strategy: canary
    canary:
      steps:
        - weight: 10
          pause: 2m
        - weight: 50
          pause: 5m
        - weight: 100
      rollback:
        automatic: true
        errorThreshold: 2

  security:
    compliance:
      gdpr: true
      pci: true  # Financial data
      dataResidency: eu

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: dhanam-web
  project: aureo-labs
  labels:
    app: dhanam
    component: web
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-org/dhanam
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"
      NEXT_PUBLIC_API_URL: https://api.dhanam.app

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  networking:
    port: 3000
    domains:
      - dhanam.app
      - www.dhanam.app
      - dhanam.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    NEXT_PUBLIC_API_URL: https://api.dhanam.app

  deployment:
    strategy: rolling
