# Enclii Documentation Site - docs.enclii.dev
# Technical documentation deployed on Enclii (dogfooding)
# Version: 0.1.0

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: docs-site
  project: enclii-platform
  description: Docusaurus documentation site for Enclii

spec:
  build:
    type: dockerfile
    dockerfile: apps/docs-site/Dockerfile
    context: .
    source:
      git:
        repository: https://github.com/madfam-org/enclii
        branch: main
        autoDeploy: true

  runtime:
    port: 4203
    replicas: 1
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

  healthCheck:
    path: /health
    intervalSeconds: 30
    timeoutSeconds: 5

  domains:
    - domain: docs.enclii.dev
      tls: true
      tlsIssuer: cloudflare

  # Aggressive caching for static docs
  caching:
    enabled: true
    ttl: 3600  # 1 hour
    headers:
      - "Cache-Control: public, max-age=3600"

  autoscaling:
    enabled: false  # Static site, single replica sufficient
