# Enclii Documentation Site - docs.enclii.io
# Technical documentation deployed on Enclii (dogfooding)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: docs-site
  project: enclii-platform
  description: Documentation site (Docusaurus or similar)

spec:
  build:
    type: nixpacks  # Auto-detect Node.js static site
    context: .
    source:
      git:
        repository: https://github.com/madfam-io/enclii
        branch: main
        path: docs  # Assuming docs live here
        autoDeploy: true

  runtime:
    port: 3000
    replicas: 2
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

  env:
    - name: NODE_ENV
      value: production
    - name: NEXT_PUBLIC_APP_URL
      value: https://app.enclii.io

  domains:
    - domain: docs.enclii.io
      tls: true
      tlsIssuer: cloudflare

  # Aggressive caching for docs
  caching:
    enabled: true
    ttl: 3600  # 1 hour
    headers:
      - "Cache-Control: public, max-age=3600"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
