# Electrochem-Sim (Galvana) - Enclii Service Specification
# Phygital electrochemistry platform (simulation + instrument control)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: galvana-api
  project: aureo-labs
  labels:
    app: galvana
    component: api
    tier: production
    team: aureo-labs

spec:
  build:
    source:
      repo: github.com/madfam-io/electrochem-sim
      branch: main
      path: .
    builder: dockerfile
    dockerfile: Dockerfile.api
    buildEnv:
      PYTHON_VERSION: "3.11"

  runtime:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi # FEniCSx simulations need memory
    replicas:
      min: 2
      max: 8
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 60
        - type: memory
          target: 70
    healthCheck:
      liveness:
        path: /health
        port: 8000
      readiness:
        path: /health/ready
        port: 8000

  networking:
    port: 8000
    domains:
      - api.galvana.io
      - galvana-api.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    ENVIRONMENT: production
    DEBUG: "false"
    LOG_LEVEL: INFO

  secrets:
    - name: DATABASE_URL
      key: galvana/database-url
    - name: SECRET_KEY
      key: galvana/secret-key
    - name: REDIS_URL
      key: shared/redis-url

  database:
    type: postgresql
    provider: shared
    name: galvana_production
    extensions:
      - uuid-ossp
      - timescaledb # Time-series data from instruments

  cache:
    type: redis
    provider: shared
    db: 7

  deployment:
    strategy: canary
    canary:
      steps:
        - weight: 10
          pause: 3m
        - weight: 50
          pause: 5m
        - weight: 100
      rollback:
        automatic: true
        errorThreshold: 2

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: galvana-web
  project: aureo-labs
  labels:
    app: galvana
    component: web
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-io/electrochem-sim
      branch: main
      path: .
    builder: dockerfile
    dockerfile: Dockerfile.web
    buildEnv:
      NODE_VERSION: "20"
      NEXT_PUBLIC_API_URL: https://api.galvana.io

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  networking:
    port: 3000
    domains:
      - galvana.io
      - www.galvana.io
      - galvana.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    NEXT_PUBLIC_API_URL: https://api.galvana.io

  deployment:
    strategy: rolling

---
# Simulation Worker (for heavy FEniCSx computations)
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: galvana-worker
  project: aureo-labs
  labels:
    app: galvana
    component: worker
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-io/electrochem-sim
      branch: main
      path: .
    builder: dockerfile
    dockerfile: Dockerfile.worker

  runtime:
    resources:
      requests:
        cpu: 1000m
        memory: 2Gi
      limits:
        cpu: 4000m
        memory: 8Gi
    replicas:
      min: 1
      max: 5
    autoscaling:
      enabled: true
      metrics:
        - type: queueDepth
          target: 10

  env:
    ENVIRONMENT: production
    WORKER_CONCURRENCY: "2"

  secrets:
    - name: DATABASE_URL
      key: galvana/database-url
    - name: REDIS_URL
      key: shared/redis-url

  # No networking - internal worker only
  networking:
    internal: true
