# Forge Sight - Enclii Service Specification
# Global Digital Fabrication Pricing Intelligence Platform
# Part of MADFAM/Aureo Labs ecosystem

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: forgesight-api
  project: aureo-labs
  labels:
    app: forgesight
    component: api
    tier: production
    team: aureo-labs

spec:
  # Build Configuration
  build:
    # Source from MADFAM GitHub org
    source:
      repo: github.com/madfam-io/digifab-harvest-benchmark
      branch: main
      path: services/api

    # Use custom Dockerfile optimized for WeasyPrint
    builder: dockerfile
    dockerfile: Dockerfile.railway  # Reuse existing Railway Dockerfile

    # Build-time environment
    buildEnv:
      PYTHON_VERSION: "3.11"

    # Build caching
    cache:
      enabled: true
      paths:
        - /root/.cache/pip

  # Runtime Configuration
  runtime:
    # Resource allocation
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi

    # Replicas
    replicas:
      min: 2
      max: 10

    # Autoscaling
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 70
        - type: memory
          target: 80
        - type: requestsPerSecond
          target: 100

    # Health checks
    healthCheck:
      liveness:
        path: /health/liveness
        port: 8000
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readiness:
        path: /health/readiness
        port: 8000
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 3

    # Startup probe for slow-starting containers
    startupProbe:
      path: /health/liveness
      port: 8000
      initialDelaySeconds: 10
      periodSeconds: 5
      failureThreshold: 30  # 150 seconds max startup

  # Networking
  networking:
    # Primary port
    port: 8000
    protocol: http

    # Custom domain
    domains:
      - api.forgesight.quest
      - forgesight-api.enclii.dev

    # TLS (automatic via Cloudflare)
    tls:
      enabled: true
      provider: cloudflare

    # CORS configuration
    cors:
      enabled: true
      origins:
        - https://www.forgesight.quest
        - https://forgesight.quest
        - https://forgesight.enclii.dev
      methods: [GET, POST, PUT, DELETE, OPTIONS, PATCH]
      headers: ["*"]
      credentials: true

  # Environment Variables
  env:
    # Core Configuration
    ENVIRONMENT: production
    DEBUG: "false"
    API_V1_STR: /api/v1

    # Security
    ALGORITHM: HS256
    ACCESS_TOKEN_EXPIRE_MINUTES: "30"

    # Rate Limiting
    RATE_LIMIT_REQUESTS: "100"
    RATE_LIMIT_PERIOD: "60"
    RATE_LIMITING_ENABLED: "true"
    REQUIRE_AUTH_FOR_API: "false"

    # Export Settings
    MAX_EXPORT_SIZE_MB: "1000"
    EXPORT_RETENTION_DAYS: "30"
    MAX_CONCURRENT_EXPORTS: "5"

    # Database Configuration
    DB_POOL_SIZE: "20"
    DB_MAX_OVERFLOW: "40"
    DB_POOL_RECYCLE: "1800"

    # CORS (also handled at networking level)
    BACKEND_CORS_ORIGINS: "https://www.forgesight.quest,https://forgesight.quest"

  # Secrets (from Enclii Lockbox)
  secrets:
    - name: SECRET_KEY
      key: forgesight/secret-key
    - name: DATABASE_URL
      key: forgesight/database-url
    - name: REDIS_URL
      key: shared/redis-url
      optional: true
    - name: MINIO_ENDPOINT
      key: shared/r2-endpoint
      optional: true
    - name: MINIO_ACCESS_KEY
      key: shared/r2-access-key
      optional: true
    - name: MINIO_SECRET_KEY
      key: shared/r2-secret-key
      optional: true
    - name: SENTRY_DSN
      key: forgesight/sentry-dsn
      optional: true

  # Database
  database:
    type: postgresql
    provider: shared  # Use shared Enclii PostgreSQL
    name: forgesight_production
    extensions:
      - uuid-ossp
      - pgcrypto
    migrations:
      enabled: true
      command: "alembic upgrade head"

  # Caching
  cache:
    type: redis
    provider: shared  # Use shared Enclii Redis Sentinel
    db: 2  # Forgesight uses Redis DB 2

  # Deployment Strategy
  deployment:
    strategy: canary
    canary:
      steps:
        - weight: 10
          pause: 2m
        - weight: 50
          pause: 5m
        - weight: 100
      analysis:
        metrics:
          - name: error-rate
            threshold: 1  # Max 1% error rate
          - name: latency-p95
            threshold: 500  # Max 500ms p95 latency
      rollback:
        automatic: true
        errorThreshold: 2  # 2% error rate triggers rollback

  # Monitoring
  monitoring:
    metrics:
      enabled: true
      path: /metrics
      port: 8000

    logging:
      level: INFO
      format: json

    tracing:
      enabled: true
      provider: opentelemetry
      samplingRate: 0.1

    alerts:
      - name: high-error-rate
        condition: error_rate > 0.01
        duration: 5m
        severity: critical
        notify: [slack, pagerduty]

      - name: high-latency
        condition: latency_p95 > 500
        duration: 5m
        severity: warning
        notify: [slack]

      - name: pod-restart
        condition: restart_count > 3
        duration: 10m
        severity: warning
        notify: [slack]

  # Security
  security:
    # Network policies
    networkPolicy:
      ingress:
        - from: cloudflare-tunnel
        - from: forgesight-web
      egress:
        - to: postgresql
        - to: redis
        - to: external  # For payment APIs, etc.

    # Pod security
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: false  # WeasyPrint needs write access
      allowPrivilegeEscalation: false

    # Compliance
    compliance:
      gdpr: true
      dataResidency: eu  # Hetzner EU datacenters

  # Dependencies
  dependencies:
    services:
      - name: postgresql
        required: true
      - name: redis
        required: false  # Graceful degradation if Redis unavailable

---
# Forge Sight Web Frontend
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: forgesight-web
  project: aureo-labs
  labels:
    app: forgesight
    component: web
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-io/digifab-harvest-benchmark
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"
      VITE_API_URL: https://api.forgesight.quest

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  networking:
    port: 3000
    domains:
      - www.forgesight.quest
      - forgesight.quest
      - forgesight.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    VITE_API_URL: https://api.forgesight.quest

  deployment:
    strategy: rolling
    maxSurge: 1
    maxUnavailable: 0
