# Forj - Enclii Service Specification
# Blockchain-capable decentralized fabrication storefront

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: forj-web
  project: aureo-labs
  labels:
    app: forj
    component: web
    tier: production
    team: aureo-labs

spec:
  build:
    source:
      repo: github.com/madfam-io/forj
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"
      NEXT_PUBLIC_API_URL: https://api.forj.io

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  networking:
    port: 3000
    domains:
      - forj.io
      - www.forj.io
      - forj.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    NEXT_PUBLIC_API_URL: https://api.forj.io

  deployment:
    strategy: rolling

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: forj-api
  project: aureo-labs
  labels:
    app: forj
    component: api
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-io/forj
      branch: main
      path: apps/api
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"

  runtime:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    replicas:
      min: 2
      max: 8
    healthCheck:
      liveness:
        path: /health
        port: 3001
      readiness:
        path: /health
        port: 3001

  networking:
    port: 3001
    domains:
      - api.forj.io
      - forj-api.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    PORT: "3001"

  secrets:
    - name: DATABASE_URL
      key: forj/database-url
    - name: SUPABASE_URL
      key: forj/supabase-url
    - name: SUPABASE_KEY
      key: forj/supabase-key
    - name: BLOCKCHAIN_RPC_URL
      key: forj/blockchain-rpc
      optional: true

  database:
    type: postgresql
    provider: shared
    name: forj_production

  deployment:
    strategy: canary
    canary:
      steps:
        - weight: 10
          pause: 2m
        - weight: 50
          pause: 5m
        - weight: 100
