# Fortuna - Enclii Service Specification
# Problem Intelligence Platform

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: fortuna-api
  project: aureo-labs
  labels:
    app: fortuna
    component: api
    tier: production
    team: aureo-labs

spec:
  build:
    source:
      repo: github.com/madfam-org/fortuna
      branch: main
      path: .
    builder: dockerfile
    dockerfile: Dockerfile
    buildEnv:
      PYTHON_VERSION: "3.11"

  runtime:
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 2Gi
    replicas:
      min: 2
      max: 10
    autoscaling:
      enabled: true
      metrics:
        - type: cpu
          target: 70
    healthCheck:
      liveness:
        path: /health
        port: 8000
      readiness:
        path: /health/ready
        port: 8000

  networking:
    port: 8000
    domains:
      - api.fortuna.quest
      - fortuna-api.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    ENVIRONMENT: production
    DEBUG: "false"
    LOG_LEVEL: INFO

  secrets:
    - name: DATABASE_URL
      key: fortuna/database-url
    - name: SECRET_KEY
      key: fortuna/secret-key
    - name: REDIS_URL
      key: shared/redis-url
    - name: OPENSEARCH_URL
      key: fortuna/opensearch-url
      optional: true

  database:
    type: postgresql
    provider: shared
    name: fortuna_production
    extensions:
      - uuid-ossp
      - pgvector # For ML embeddings

  cache:
    type: redis
    provider: shared
    db: 4

  deployment:
    strategy: canary
    canary:
      steps:
        - weight: 10
          pause: 2m
        - weight: 50
          pause: 5m
        - weight: 100
      rollback:
        automatic: true
        errorThreshold: 2

---
# NLP Service (for problem analysis)
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: fortuna-nlp
  project: aureo-labs
  labels:
    app: fortuna
    component: nlp
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-org/fortuna
      branch: main
      path: services/nlp
    builder: dockerfile

  runtime:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 4Gi
    replicas:
      min: 1
      max: 5
    healthCheck:
      liveness:
        path: /health
        port: 8001
      readiness:
        path: /health
        port: 8001

  networking:
    port: 8001
    internal: true # Only accessible from fortuna-api

  env:
    ENVIRONMENT: production

  secrets:
    - name: OPENAI_API_KEY
      key: shared/openai-api-key
      optional: true

  deployment:
    strategy: rolling

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: fortuna-web
  project: aureo-labs
  labels:
    app: fortuna
    component: web
    tier: production

spec:
  build:
    source:
      repo: github.com/madfam-org/fortuna
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"
      NEXT_PUBLIC_API_URL: https://api.fortuna.quest

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  networking:
    port: 3000
    domains:
      - fortuna.quest
      - www.fortuna.quest
      - fortuna.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    NEXT_PUBLIC_API_URL: https://api.fortuna.quest

  deployment:
    strategy: rolling
