# Janua Authentication Service Specification
# Self-hosted OAuth 2.0 / OIDC provider for Enclii platform
#
# Janua provides:
# - OAuth 2.0 Authorization Server
# - OpenID Connect Provider
# - User management and authentication
# - SSO support (SAML, LDAP, social providers)
# - Multi-tenant support
#
# Repository: https://github.com/madfam-io/janua
# License: AGPL v3

apiVersion: enclii.io/v1
kind: Service
metadata:
  name: janua
  namespace: enclii-platform
  labels:
    app: janua
    tier: authentication
    criticality: high
  annotations:
    enclii.io/description: "Self-hosted OAuth/OIDC authentication service"
    enclii.io/owner: platform-team
    enclii.io/runbook: "https://docs.enclii.io/runbooks/janua"

spec:
  # ==========================================================================
  # SOURCE CONFIGURATION
  # ==========================================================================
  source:
    git:
      repository: https://github.com/madfam-io/janua
      branch: main
      # Monorepo path to API service
      path: apps/api

    # Build configuration
    build:
      type: dockerfile
      dockerfile: apps/api/Dockerfile
      context: .
      args:
        - name: NODE_ENV
          value: production
        - name: BUILD_VERSION
          valueFrom:
            gitRef: true

      # Build provenance and security
      provenance:
        enabled: true
        sbom: true
        signing: true
        attestation:
          enabled: true
          predicateType: https://slsa.dev/provenance/v1

  # ==========================================================================
  # DEPLOYMENT CONFIGURATION
  # ==========================================================================
  deployment:
    replicas: 3  # Authentication is critical - always HA

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0  # Zero downtime for auth

    # Container configuration
    container:
      port: 5556

      # Health checks - stricter for auth
      healthCheck:
        path: /health
        port: 5556
        initialDelaySeconds: 10
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 2
        successThreshold: 1

      # Readiness check
      readinessCheck:
        path: /ready
        port: 5556
        initialDelaySeconds: 5
        periodSeconds: 3
        timeoutSeconds: 2
        failureThreshold: 2

      # Resource limits
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
        limits:
          cpu: "1000m"
          memory: "1Gi"

      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

    # Pod configuration
    pod:
      labels:
        app: janua
        version: "${BUILD_VERSION}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5556"
        prometheus.io/path: "/metrics"

      # Anti-affinity for HA
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: janua
              topologyKey: kubernetes.io/hostname

  # ==========================================================================
  # AUTOSCALING
  # ==========================================================================
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 70
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
    # Scale up quickly for auth (login spikes)
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
          - type: Percent
            value: 100
            periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 25
            periodSeconds: 120

  # ==========================================================================
  # NETWORKING
  # ==========================================================================
  networking:
    # Primary domain for auth
    domains:
      - name: auth.enclii.io
        primary: true
        tls:
          enabled: true
          provider: cloudflare

    # Internal service
    service:
      type: ClusterIP
      port: 5556
      targetPort: 5556

    # Ingress rules
    ingress:
      enabled: true
      annotations:
        # Security headers for auth service
        nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header X-Frame-Options "DENY" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header X-XSS-Protection "1; mode=block" always;
          add_header Referrer-Policy "strict-origin-when-cross-origin" always;
          add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:; frame-ancestors 'none';" always;

      # Rate limiting for auth endpoints
      rateLimit:
        enabled: true
        requestsPerMinute: 60  # Stricter for auth
        burst: 20

  # ==========================================================================
  # ENVIRONMENT CONFIGURATION
  # ==========================================================================
  env:
    # Application mode
    - name: NODE_ENV
      value: production

    # Server configuration
    - name: PORT
      value: "5556"
    - name: HOST
      value: "0.0.0.0"

    # Issuer URL (critical for OIDC)
    - name: ISSUER_URL
      value: "https://auth.enclii.io"

    # Database (from secret)
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: janua-secrets
          key: database-url

    # Redis for sessions
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: janua-secrets
          key: redis-url

    # Session configuration
    - name: SESSION_SECRET
      valueFrom:
        secretKeyRef:
          name: janua-secrets
          key: session-secret

    # SMTP for emails (password reset, verification)
    - name: SMTP_HOST
      valueFrom:
        secretKeyRef:
          name: janua-secrets
          key: smtp-host
    - name: SMTP_PORT
      valueFrom:
        secretKeyRef:
          name: janua-secrets
          key: smtp-port
    - name: SMTP_USER
      valueFrom:
        secretKeyRef:
          name: janua-secrets
          key: smtp-user
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: janua-secrets
          key: smtp-password
    - name: SMTP_FROM
      value: "noreply@enclii.io"

    # Enclii OAuth client configuration
    - name: ENCLII_CLIENT_ID
      value: "enclii-switchyard"
    - name: ENCLII_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: janua-secrets
          key: enclii-client-secret
    - name: ENCLII_REDIRECT_URIS
      value: "https://app.enclii.io/auth/callback,https://api.enclii.io/api/v1/auth/oidc/callback"

    # Security settings
    - name: BCRYPT_ROUNDS
      value: "12"
    - name: TOKEN_EXPIRY_ACCESS
      value: "15m"
    - name: TOKEN_EXPIRY_REFRESH
      value: "7d"
    - name: TOKEN_EXPIRY_ID
      value: "1h"

    # Logging
    - name: LOG_LEVEL
      value: "info"
    - name: LOG_FORMAT
      value: "json"

  # ==========================================================================
  # VOLUMES
  # ==========================================================================
  volumes:
    # RSA keys for JWT signing
    - name: jwt-keys
      mountPath: /app/keys
      secret:
        secretName: janua-jwt-keys
        items:
          - key: private-key
            path: private.pem
            mode: 0400
          - key: public-key
            path: public.pem
            mode: 0444

    # Temporary directory for uploads (if any)
    - name: tmp
      mountPath: /tmp
      emptyDir:
        sizeLimit: 100Mi

  # ==========================================================================
  # DEPLOYMENT PIPELINE
  # ==========================================================================
  pipeline:
    # Automatic deployment on main branch
    autoDeploy: true

    # Deployment stages
    stages:
      - name: build
        timeout: 600  # 10 minutes max

      - name: security-scan
        image: aquasec/trivy:latest
        args: ["image", "--severity", "HIGH,CRITICAL", "--exit-code", "1"]

      - name: deploy-canary
        replicas: 1
        duration: 300  # 5 minutes
        analysis:
          metrics:
            - name: error_rate
              threshold: 1  # Very strict for auth - 1% max
              operator: lessThan
            - name: latency_p99
              threshold: 200  # 200ms p99 latency
              operator: lessThan
            - name: login_success_rate
              threshold: 99  # 99% login success
              operator: greaterThan

      - name: deploy-production
        strategy: rolling
        rollbackOnFailure: true

    # Webhooks for notifications
    webhooks:
      onSuccess:
        - url: "${SLACK_WEBHOOK_URL}"
          payload: |
            {
              "text": "✅ Janua deployed successfully to production",
              "attachments": [{
                "color": "good",
                "fields": [
                  {"title": "Service", "value": "janua", "short": true},
                  {"title": "Version", "value": "${BUILD_VERSION}", "short": true}
                ]
              }]
            }
      onFailure:
        - url: "${SLACK_WEBHOOK_URL}"
          payload: |
            {
              "text": "❌ Janua deployment failed",
              "attachments": [{
                "color": "danger",
                "fields": [
                  {"title": "Service", "value": "janua", "short": true},
                  {"title": "Error", "value": "${ERROR_MESSAGE}", "short": false}
                ]
              }]
            }

  # ==========================================================================
  # MONITORING
  # ==========================================================================
  monitoring:
    # Prometheus metrics
    prometheus:
      enabled: true
      path: /metrics
      port: 5556

    # Custom metrics for auth
    customMetrics:
      - name: janua_login_total
        type: counter
        description: "Total login attempts"
        labels: ["method", "success"]
      - name: janua_token_issued_total
        type: counter
        description: "Total tokens issued"
        labels: ["type", "client_id"]
      - name: janua_active_sessions
        type: gauge
        description: "Number of active sessions"

    # Alerts
    alerts:
      - name: JanuaHighErrorRate
        condition: rate(janua_login_total{success="false"}[5m]) > 0.1
        duration: 5m
        severity: critical
        annotations:
          summary: "High login failure rate"
          description: "Login failure rate is above 10% for 5 minutes"

      - name: JanuaHighLatency
        condition: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{service="janua"}[5m])) > 0.5
        duration: 5m
        severity: warning
        annotations:
          summary: "High authentication latency"
          description: "99th percentile latency is above 500ms"

      - name: JanuaLowAvailability
        condition: up{service="janua"} < 2
        duration: 2m
        severity: critical
        annotations:
          summary: "Janua availability degraded"
          description: "Less than 2 Janua replicas are available"

  # ==========================================================================
  # COMPLIANCE
  # ==========================================================================
  compliance:
    # Security requirements for auth service
    requirements:
      - id: AUTH-001
        description: "All authentication tokens must use RS256 signing"
        status: implemented
      - id: AUTH-002
        description: "Password hashing must use bcrypt with minimum 12 rounds"
        status: implemented
      - id: AUTH-003
        description: "Session tokens must be revocable"
        status: implemented
      - id: AUTH-004
        description: "All auth endpoints must be rate limited"
        status: implemented
      - id: AUTH-005
        description: "OIDC discovery must be available at /.well-known/openid-configuration"
        status: implemented

    # Audit logging
    audit:
      enabled: true
      events:
        - login_success
        - login_failure
        - logout
        - password_change
        - password_reset
        - token_issued
        - token_revoked
        - user_created
        - user_deleted
        - permission_changed
