# Janua Admin Service Specification
# Internal administration dashboard for Janua
#
# Repository: https://github.com/madfam-io/janua
# Path: apps/admin
# Port: 4102 (per PORT_ALLOCATION.md)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: janua-admin
  project: janua
  description: Janua internal admin dashboard

spec:
  # Build configuration
  build:
    type: dockerfile
    dockerfile: apps/admin/Dockerfile
    context: .
    source:
      git:
        repository: https://github.com/madfam-io/janua
        branch: main
        path: apps/admin
        autoDeploy: true

  runtime:
    port: 3000
    replicas: 2
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    healthCheck: /api/health
    readinessProbe:
      path: /api/health
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      path: /api/health
      initialDelaySeconds: 30
      periodSeconds: 10

  # Environment variables
  env:
    - name: NODE_ENV
      value: production
    - name: NEXT_PUBLIC_API_URL
      value: https://api.janua.madfam.io

  # Networking
  routes:
    - host: admin.janua.madfam.io
      path: /
      tls: true

  # Observability
  observability:
    logs:
      enabled: true
      format: json
    metrics:
      enabled: true
      path: /metrics
