# Janua Website Service Specification
# Public website for Janua
#
# Repository: https://github.com/madfam-org/janua
# Path: apps/website
# Port: 4104 (per PORT_ALLOCATION.md)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: janua-website
  project: janua
  description: Janua public website

spec:
  # Build configuration
  build:
    type: dockerfile
    dockerfile: apps/website/Dockerfile
    context: .
    source:
      git:
        repository: https://github.com/madfam-org/janua
        branch: main
        path: apps/website
        autoDeploy: true

  runtime:
    port: 3000
    replicas: 2
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"

    healthCheck: /
    readinessProbe:
      path: /
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      path: /
      initialDelaySeconds: 15
      periodSeconds: 10

  # Environment variables
  env:
    - name: NODE_ENV
      value: production
    - name: NEXT_PUBLIC_API_URL
      value: https://api.janua.madfam.io

  # Networking
  routes:
    - host: janua.madfam.io
      path: /
      tls: true

  # Observability
  observability:
    logs:
      enabled: true
      format: json
