# Janua Docs Service Specification
# Documentation site for Janua
#
# Repository: https://github.com/madfam-org/janua
# Path: apps/docs
# Port: 4103 (per PORT_ALLOCATION.md)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: janua-docs
  project: janua
  description: Janua documentation site

spec:
  # Build configuration
  build:
    type: dockerfile
    dockerfile: apps/docs/Dockerfile
    context: .
    source:
      git:
        repository: https://github.com/madfam-org/janua
        branch: main
        path: apps/docs
        autoDeploy: true

  runtime:
    port: 3000
    replicas: 2
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"

    healthCheck: /
    readinessProbe:
      path: /
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      path: /
      initialDelaySeconds: 15
      periodSeconds: 10

  # Environment variables
  env:
    - name: NODE_ENV
      value: production

  # Networking
  routes:
    - host: docs.janua.madfam.io
      path: /
      tls: true

  # Observability
  observability:
    logs:
      enabled: true
      format: json
