# Enclii Landing Page - enclii.io
# Marketing site deployed on Enclii (dogfooding)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: landing-page
  project: enclii-platform
  description: Public marketing site (Next.js static export)

spec:
  build:
    type: nixpacks  # Auto-detect Next.js
    context: .
    buildArgs:
      - name: NEXT_PUBLIC_APP_URL
        value: https://app.enclii.io
      - name: NODE_ENV
        value: production
    source:
      git:
        repository: https://github.com/madfam-org/enclii
        branch: main
        path: apps/landing  # Assuming landing page lives here
        autoDeploy: true

  runtime:
    port: 3000
    replicas: 2
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

  env:
    - name: NODE_ENV
      value: production
    - name: NEXT_PUBLIC_APP_URL
      value: https://app.enclii.io
    - name: NEXT_PUBLIC_DOCS_URL
      value: https://docs.enclii.io
    - name: NEXT_PUBLIC_STATUS_URL
      value: https://status.enclii.io

  domains:
    - domain: enclii.io
      tls: true
      tlsIssuer: cloudflare
    - domain: www.enclii.io
      tls: true
      tlsIssuer: cloudflare

  # Aggressive caching for static marketing site
  caching:
    enabled: true
    ttl: 86400  # 24 hours
    headers:
      - "Cache-Control: public, max-age=86400, s-maxage=86400"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    targetCPUUtilizationPercentage: 70
