# MADFAM Corporate Website - Enclii Service Specification
# Corporate website showcasing MADFAM ecosystem

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: madfam-site
  project: madfam
  labels:
    app: madfam-site
    component: web
    tier: production
    team: madfam

spec:
  build:
    source:
      repo: github.com/madfam-io/biz-site
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"
      NEXT_TELEMETRY_DISABLED: "1"

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /api/health
        port: 3000
      readiness:
        path: /api/health
        port: 3000

  networking:
    port: 3000
    domains:
      - madfam.io
      - www.madfam.io
      - madfam.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    NEXT_TELEMETRY_DISABLED: "1"

  deployment:
    strategy: rolling
    maxSurge: 1
    maxUnavailable: 0

  monitoring:
    metrics:
      enabled: true
    logging:
      level: INFO
