# npm-registry.yaml
# Enclii Service Definition for npm.madfam.io
# MADFAM Private Package Registry powered by Verdaccio

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: npm-registry
  project: enclii-platform
  description: |
    MADFAM private npm registry at npm.madfam.io.
    Hosts all @madfam, @janua, @dhanam, @cotiza, @fortuna, @avala,
    @forgesight, @coforma, @forj, and @enclii scoped packages.
  labels:
    tier: infrastructure
    criticality: high
    team: platform

spec:
  # Use official Verdaccio image
  image: verdaccio/verdaccio:5

  runtime:
    port: 4873
    replicas: 2
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

  env:
    - name: VERDACCIO_PORT
      value: "4873"
    - name: VERDACCIO_PUBLIC_URL
      value: "https://npm.madfam.io"

  # Persistent storage for packages
  volumes:
    - name: storage
      mountPath: /verdaccio/storage
      size: 50Gi
      storageClassName: hetzner-volumes
    - name: config
      mountPath: /verdaccio/conf/config.yaml
      subPath: config.yaml
      configMapRef:
        name: verdaccio-config
    - name: htpasswd
      mountPath: /verdaccio/conf/htpasswd
      subPath: htpasswd
      secretRef:
        name: verdaccio-auth

  # Custom domain with Cloudflare TLS
  domains:
    - domain: npm.madfam.io
      tls: true
      tlsIssuer: cloudflare

  # Health monitoring
  healthCheck: /-/ping

  readinessProbe:
    path: /-/ping
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3

  livenessProbe:
    path: /-/ping
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5

  # Autoscaling configuration
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # Service Level Objectives
  slo:
    availability: 99.9
    latencyP95: 200
    errorRate: 0.5

  # Backup configuration
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM UTC
    retention: 30          # Keep 30 days of backups
    destination: r2://madfam-backups/npm-registry

  # Network policy - restrict to ingress only
  networkPolicy:
    ingress:
      - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: ingress-nginx
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: cloudflare
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
        ports:
          - protocol: TCP
            port: 443  # For npmjs.org uplink

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

  # Pod anti-affinity for HA
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: verdaccio
            topologyKey: kubernetes.io/hostname

  # Annotations for monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4873"
    prometheus.io/path: "/-/metrics"

---
# ConfigMap managed separately for easier updates
apiVersion: v1
kind: ConfigMap
metadata:
  name: verdaccio-config
  namespace: npm-registry
data:
  config.yaml: |
    # See infra/k8s/base/verdaccio/configmap.yaml for full config
    # This is managed by Kustomize
