# Primavera3D - Enclii Service Specification
# 3D modeling & digital fabrication services portfolio

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: primavera3d
  project: primavera3d
  labels:
    app: primavera3d
    component: web
    tier: production
    team: primavera3d

spec:
  build:
    source:
      repo: github.com/madfam-io/primavera3d
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"
      NEXT_TELEMETRY_DISABLED: "1"

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /api/health
        port: 3000
      readiness:
        path: /api/health
        port: 3000

  networking:
    port: 3000
    domains:
      - primavera3d.com
      - www.primavera3d.com
      - primavera3d.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production
    NEXT_TELEMETRY_DISABLED: "1"

  secrets:
    - name: SANITY_API_TOKEN
      key: primavera3d/sanity-token
      optional: true

  deployment:
    strategy: rolling
    maxSurge: 1
    maxUnavailable: 0
