# Sim4D (BrepFlow) - Enclii Service Specification
# Browser-based parametric CAD with exact geometry

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: sim4d-web
  project: aureo-labs
  labels:
    app: sim4d
    component: web
    tier: production
    team: aureo-labs

spec:
  build:
    source:
      repo: github.com/madfam-io/brepflow
      branch: main
      path: apps/web
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    replicas:
      min: 2
      max: 5
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  networking:
    port: 3000
    domains:
      - sim4d.io
      - www.sim4d.io
      - sim4d.enclii.dev
    tls:
      enabled: true
      provider: cloudflare

  env:
    NODE_ENV: production

  deployment:
    strategy: rolling
    maxSurge: 1
    maxUnavailable: 0
