# Solarpunk Foundry - Enclii Service Specification
# MADFAM shared infrastructure, SDKs, and developer tools monorepo

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: solarpunk-docs
  project: madfam-platform
  labels:
    app: solarpunk-foundry
    component: docs
    tier: production
    team: madfam
  annotations:
    description: "MADFAM developer documentation and design system showcase"

spec:
  build:
    source:
      repo: github.com/madfam-org/solarpunk-foundry
      branch: main
      path: apps/docs
    builder: nixpacks
    buildEnv:
      NODE_VERSION: "20"

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    replicas:
      min: 2
      max: 4
    healthCheck:
      liveness:
        path: /
        port: 3000
      readiness:
        path: /
        port: 3000

  routes:
    - host: docs.madfam.io
      path: /
      port: 3000

  env:
    - name: NODE_ENV
      value: production

  deployment:
    strategy: rolling
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

---
apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: solarpunk-storybook
  project: madfam-platform
  labels:
    app: solarpunk-foundry
    component: storybook
    tier: production
  annotations:
    description: "Design system component showcase"

spec:
  build:
    source:
      repo: github.com/madfam-org/solarpunk-foundry
      branch: main
      path: packages/ui
    builder: dockerfile
    dockerfile: Dockerfile.storybook
    buildCommand: npm run build-storybook

  runtime:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
    replicas:
      min: 2
      max: 3
    healthCheck:
      liveness:
        path: /
        port: 80
      readiness:
        path: /
        port: 80

  routes:
    - host: ui.madfam.io
      path: /
      port: 80

  env:
    - name: NODE_ENV
      value: production
