# Enclii Status Page - status.enclii.io
# Public uptime monitoring deployed on Enclii (dogfooding)

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: status-page
  project: enclii-platform
  description: Public status and uptime monitoring

spec:
  build:
    type: dockerfile
    dockerfile: Dockerfile
    context: .
    source:
      git:
        repository: https://github.com/madfam-org/enclii
        branch: main
        path: apps/status  # Assuming status page app here
        autoDeploy: true

  runtime:
    port: 3000
    replicas: 2
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

    healthCheck: /health

  env:
    - name: NODE_ENV
      value: production
    - name: API_URL
      value: https://api.enclii.io/health

    # Prometheus for metrics
    - name: PROMETHEUS_URL
      valueFrom:
        secretKeyRef:
          name: enclii-secrets
          key: prometheus-url

  domains:
    - domain: status.enclii.io
      tls: true
      tlsIssuer: cloudflare

  # Monitor these services
  monitoring:
    targets:
      - name: Control Plane API
        url: https://api.enclii.io/health
        expectedStatus: 200
        interval: 30s
      - name: Web Dashboard
        url: https://app.enclii.io/api/health
        expectedStatus: 200
        interval: 30s
      - name: Authentication
        url: https://auth.enclii.io/health
        expectedStatus: 200
        interval: 30s
      - name: Documentation
        url: https://docs.enclii.io
        expectedStatus: 200
        interval: 60s

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
