# Enclii Web UI - Self-Hosted on Enclii
# This service spec deploys the Next.js web interface using Enclii itself

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: switchyard-ui
  project: enclii-platform
  description: Enclii web dashboard (Next.js) - dogfooding

spec:
  # Build from the Enclii repository
  build:
    type: nixpacks  # Auto-detect Next.js and build optimally
    context: apps/switchyard-ui
    buildArgs:
      - name: NEXT_PUBLIC_API_URL
        value: https://api.enclii.io
      - name: NEXT_PUBLIC_AUTH_URL
        value: https://auth.enclii.io
      - name: NODE_ENV
        value: production
    source:
      git:
        repository: https://github.com/madfam-io/enclii
        branch: main
        path: apps/switchyard-ui  # Build only this subdirectory
        autoDeploy: true

  runtime:
    port: 3000
    replicas: 2
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

    # Health checks
    healthCheck: /api/health
    readinessProbe:
      path: /api/health
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      path: /api/health
      initialDelaySeconds: 15
      periodSeconds: 10

  # Environment variables
  env:
    - name: PORT
      value: "3000"
    - name: NODE_ENV
      value: production

    # API configuration
    - name: NEXT_PUBLIC_API_URL
      value: https://api.enclii.io
    - name: API_URL_INTERNAL
      value: http://switchyard-api.enclii-platform.svc.cluster.local:8080

    # Plinto OAuth configuration
    - name: NEXT_PUBLIC_AUTH_URL
      value: https://auth.enclii.io
    - name: NEXT_PUBLIC_AUTH_CLIENT_ID
      value: enclii-web-ui
    - name: NEXT_PUBLIC_AUTH_REDIRECT_URI
      value: https://app.enclii.io/callback
    - name: NEXT_PUBLIC_AUTH_SCOPE
      value: openid profile email

    # Analytics & monitoring (optional)
    - name: NEXT_PUBLIC_ANALYTICS_ENABLED
      value: "true"
    - name: NEXT_TELEMETRY_DISABLED
      value: "1"  # Disable Next.js telemetry

  # Custom domains
  domains:
    - domain: app.enclii.io
      tls: true
      tlsIssuer: cloudflare
    - domain: dashboard.enclii.io  # Alternative domain
      tls: true
      tlsIssuer: cloudflare

  # Autoscaling
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

  # Caching strategy
  caching:
    enabled: true
    ttl: 3600  # 1 hour cache for static assets
    headers:
      - "Cache-Control: public, max-age=3600, immutable"

---
# Network policy for Switchyard UI
# Allow traffic from:
# - Ingress controller
# Allow traffic to:
# - Switchyard API
# - Plinto

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: switchyard-ui-netpol
  namespace: enclii-platform
spec:
  podSelector:
    matchLabels:
      app: switchyard-ui
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: cloudflare-tunnel
      ports:
        - protocol: TCP
          port: 3000
  egress:
    # To Switchyard API
    - to:
        - podSelector:
            matchLabels:
              app: switchyard-api
      ports:
        - protocol: TCP
          port: 8080
    # To Plinto
    - to:
        - podSelector:
            matchLabels:
              app: plinto
      ports:
        - protocol: TCP
          port: 8000
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTPS for external APIs
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
