# Enclii Control Plane API - Self-Hosted on Enclii
# This service spec deploys the Switchyard API using Enclii itself

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: switchyard-api
  project: enclii-platform
  description: Enclii control plane REST API (dogfooding)

spec:
  # Build from the Enclii repository
  build:
    type: dockerfile
    dockerfile: apps/switchyard-api/Dockerfile
    context: .
    source:
      git:
        repository: https://github.com/madfam-org/enclii
        branch: main
        # Auto-deploy on push to main (continuous deployment)
        autoDeploy: true

  runtime:
    port: 8080
    replicas: 3
    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "1000m"
        memory: "512Mi"

    # Health checks
    healthCheck: /health
    readinessProbe:
      path: /health/ready
      initialDelaySeconds: 10
      periodSeconds: 5
    livenessProbe:
      path: /health/live
      initialDelaySeconds: 30
      periodSeconds: 10

  # Environment variables
  env:
    - name: PORT
      value: "8080"
    - name: GIN_MODE
      value: release
    - name: LOG_LEVEL
      value: info
    - name: LOG_FORMAT
      value: json

    # Database connection (Ubicloud managed PostgreSQL)
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: enclii-secrets
          key: database-url

    # Redis connection (self-hosted Sentinel)
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: enclii-secrets
          key: redis-url

    # Janua OAuth configuration
    - name: OIDC_ISSUER
      value: https://auth.enclii.io
    - name: OIDC_JWKS_URL
      value: https://auth.enclii.io/.well-known/jwks.json
    - name: OIDC_AUDIENCE
      value: enclii-api

    # JWT configuration (for issuing our own tokens)
    - name: JWT_ISSUER
      value: https://api.enclii.io
    - name: JWT_PRIVATE_KEY_PATH
      value: /secrets/jwt/private-key.pem
    - name: JWT_PUBLIC_KEY_PATH
      value: /secrets/jwt/public-key.pem

    # Object storage (Cloudflare R2)
    - name: R2_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: enclii-secrets
          key: r2-endpoint
    - name: R2_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: enclii-secrets
          key: r2-access-key-id
    - name: R2_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: enclii-secrets
          key: r2-secret-access-key
    - name: R2_BUCKET
      value: enclii-production-artifacts

    # Kubernetes API access
    - name: KUBERNETES_NAMESPACE
      value: enclii-workloads
    - name: IN_CLUSTER
      value: "true"

  # Persistent volumes for local caches
  volumes:
    - name: build-cache
      mountPath: /var/cache/enclii
      size: 20Gi
      storageClassName: hetzner-ssd
      accessMode: ReadWriteOnce

  # Custom domains
  domains:
    - domain: api.enclii.io
      tls: true
      tlsIssuer: cloudflare # Using Cloudflare for SaaS

  # Autoscaling based on CPU and memory
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80

  # Service-level objectives
  slo:
    availability: 99.95 # 99.95% uptime target
    latencyP95: 200 # P95 latency < 200ms
    errorRate: 0.5 # Error rate < 0.5%

---
# Network policy for Switchyard API
# Only allow traffic from:
# - Switchyard UI
# - Janua (for OIDC verification)
# - Ingress controller
# - Reconcilers

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: switchyard-api-netpol
  namespace: enclii-platform
spec:
  podSelector:
    matchLabels:
      app: switchyard-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: cloudflare-tunnel
      ports:
        - protocol: TCP
          port: 8080
    - from:
        - podSelector:
            matchLabels:
              app: switchyard-ui
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: postgres
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - namespaceSelector:
            matchLabels:
              name: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              app: janua
      ports:
        - protocol: TCP
          port: 8000
    # Allow DNS
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTPS for external APIs (R2, GitHub, etc.)
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
