# Twenty CRM Service Specification
# Open-source CRM platform for MADFAM ecosystem
#
# Twenty CRM provides:
# - Modern CRM with GraphQL API
# - Contact & Company management
# - Pipeline and deal tracking
# - Activity logging and timeline
# - Email integration
# - Extensible with custom objects
#
# Repository: https://github.com/twentyhq/twenty
# License: AGPL-3.0
#
# Integration with MADFAM:
# - Lead capture from madfam.io webhooks
# - Janua SSO authentication
# - Sync with product demos and trials

apiVersion: enclii.io/v1
kind: Service
metadata:
  name: twenty-crm
  namespace: madfam-platform
  labels:
    app: twenty-crm
    tier: business-tools
    criticality: high
  annotations:
    enclii.dev/description: "Open-source CRM for MADFAM sales and customer management"
    enclii.dev/owner: business-team
    enclii.dev/runbook: "https://docs.enclii.dev/runbooks/twenty-crm"
    enclii.dev/integration: "janua,madfam-site,aureo-labs"

spec:
  # ==========================================================================
  # SOURCE CONFIGURATION
  # ==========================================================================
  source:
    git:
      repository: https://github.com/twentyhq/twenty
      branch: main
      # Twenty uses a monorepo structure
      path: packages/twenty-server

    # Build configuration
    build:
      type: dockerfile
      dockerfile: packages/twenty-docker/twenty/Dockerfile
      context: .
      args:
        - name: NODE_ENV
          value: production

      # Build provenance
      provenance:
        enabled: true
        sbom: true
        signing: true

  # ==========================================================================
  # DEPLOYMENT CONFIGURATION
  # ==========================================================================
  deployment:
    replicas: 2

    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0

    # Container configuration
    container:
      port: 3000

      # Health checks
      healthCheck:
        path: /healthz
        port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
        successThreshold: 1

      # Readiness check
      readinessCheck:
        path: /healthz
        port: 3000
        initialDelaySeconds: 15
        periodSeconds: 5
        timeoutSeconds: 3
        failureThreshold: 2

      # Resource limits
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "2000m"
          memory: "4Gi"

      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        readOnlyRootFilesystem: false # Twenty needs write access
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

    # Pod configuration
    pod:
      labels:
        app: twenty-crm
        version: "${BUILD_VERSION}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"

  # ==========================================================================
  # AUTOSCALING
  # ==========================================================================
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 6
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 70
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
    behavior:
      scaleUp:
        stabilizationWindowSeconds: 120
        policies:
          - type: Percent
            value: 50
            periodSeconds: 60
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Percent
            value: 25
            periodSeconds: 120

  # ==========================================================================
  # NETWORKING
  # ==========================================================================
  networking:
    # Primary domain
    domains:
      - name: crm.madfam.io
        primary: true
        tls:
          enabled: true
          provider: cloudflare
      - name: crm.enclii.dev
        primary: false
        tls:
          enabled: true
          provider: cloudflare

    # Internal service
    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000

    # Ingress rules
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          add_header X-Frame-Options "SAMEORIGIN" always;
          add_header X-Content-Type-Options "nosniff" always;
          add_header X-XSS-Protection "1; mode=block" always;

      # Rate limiting
      rateLimit:
        enabled: true
        requestsPerMinute: 300
        burst: 50

  # ==========================================================================
  # TWENTY FRONTEND SERVICE
  # ==========================================================================
  additionalServices:
    - name: twenty-front
      source:
        git:
          repository: https://github.com/twentyhq/twenty
          branch: main
          path: packages/twenty-front
        build:
          type: dockerfile
          dockerfile: packages/twenty-docker/twenty-front/Dockerfile
          context: .
      deployment:
        replicas: 2
        container:
          port: 3001
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      networking:
        domains:
          - name: app.crm.madfam.io
            primary: true
            tls:
              enabled: true

  # ==========================================================================
  # ENVIRONMENT CONFIGURATION
  # ==========================================================================
  env:
    # Application mode
    - name: NODE_ENV
      value: production

    # Server configuration
    - name: PORT
      value: "3000"
    - name: SERVER_URL
      value: "https://crm.madfam.io"
    - name: FRONT_BASE_URL
      value: "https://app.crm.madfam.io"

    # Database
    - name: PG_DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: database-url

    # Redis
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: redis-url

    # Storage (S3-compatible - Cloudflare R2)
    - name: STORAGE_TYPE
      value: "s3"
    - name: STORAGE_S3_REGION
      value: "auto"
    - name: STORAGE_S3_NAME
      value: "twenty-crm-files"
    - name: STORAGE_S3_ENDPOINT
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: r2-endpoint
    - name: STORAGE_S3_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: r2-access-key
    - name: STORAGE_S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: r2-secret-key

    # =========================================================================
    # JANUA SSO INTEGRATION
    # =========================================================================
    - name: AUTH_SSO_ENABLED
      value: "true"
    - name: AUTH_SSO_PROVIDER
      value: "oidc"
    - name: AUTH_OIDC_ISSUER
      value: "https://auth.janua.dev"
    - name: AUTH_OIDC_CLIENT_ID
      value: "twenty-crm"
    - name: AUTH_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: janua-client-secret
    - name: AUTH_OIDC_CALLBACK_URL
      value: "https://crm.madfam.io/auth/oidc/callback"
    - name: AUTH_OIDC_SCOPES
      value: "openid profile email"

    # =========================================================================
    # MADFAM WEBHOOK INTEGRATION
    # =========================================================================
    - name: WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: webhook-secret

    # Email (SMTP)
    - name: EMAIL_FROM_ADDRESS
      value: "crm@madfam.io"
    - name: EMAIL_FROM_NAME
      value: "MADFAM CRM"
    - name: EMAIL_DRIVER
      value: "smtp"
    - name: EMAIL_SMTP_HOST
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: smtp-host
    - name: EMAIL_SMTP_PORT
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: smtp-port
    - name: EMAIL_SMTP_USER
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: smtp-user
    - name: EMAIL_SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: twenty-crm-secrets
          key: smtp-password

    # Logging
    - name: LOG_LEVEL
      value: "info"
    - name: LOG_FORMAT
      value: "json"

    # API settings
    - name: API_RATE_LIMITING_TTL
      value: "60"
    - name: API_RATE_LIMITING_LIMIT
      value: "300"

  # ==========================================================================
  # VOLUMES
  # ==========================================================================
  volumes:
    # Local file cache
    - name: cache
      mountPath: /app/.twenty-cache
      emptyDir:
        sizeLimit: 1Gi

    # Temporary directory
    - name: tmp
      mountPath: /tmp
      emptyDir:
        sizeLimit: 500Mi

  # ==========================================================================
  # DATABASE MIGRATIONS
  # ==========================================================================
  migrations:
    enabled: true
    command: ["npx", "prisma", "migrate", "deploy"]
    timeout: 300

  # ==========================================================================
  # CRON JOBS
  # ==========================================================================
  jobs:
    # Sync contacts from external sources daily
    - name: sync-contacts
      schedule: "0 2 * * *" # 2 AM daily
      command: ["node", "dist/jobs/sync-contacts.js"]
      timeout: 3600
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"

    # Clean up old activities weekly
    - name: cleanup-activities
      schedule: "0 3 * * 0" # 3 AM Sunday
      command: ["node", "dist/jobs/cleanup-activities.js"]
      timeout: 1800

    # Generate weekly reports
    - name: weekly-reports
      schedule: "0 6 * * 1" # 6 AM Monday
      command: ["node", "dist/jobs/generate-reports.js"]
      timeout: 1800

  # ==========================================================================
  # DEPLOYMENT PIPELINE
  # ==========================================================================
  pipeline:
    autoDeploy: true

    stages:
      - name: build
        timeout: 900 # 15 minutes

      - name: security-scan
        image: aquasec/trivy:latest
        args: ["image", "--severity", "HIGH,CRITICAL", "--exit-code", "1"]

      - name: deploy-canary
        replicas: 1
        duration: 300
        analysis:
          metrics:
            - name: error_rate
              threshold: 5
              operator: lessThan
            - name: latency_p99
              threshold: 1000
              operator: lessThan

      - name: deploy-production
        strategy: rolling
        rollbackOnFailure: true

    webhooks:
      onSuccess:
        - url: "${SLACK_WEBHOOK_URL}"
          payload: |
            {
              "text": "✅ Twenty CRM deployed successfully",
              "attachments": [{
                "color": "good",
                "fields": [
                  {"title": "Service", "value": "twenty-crm", "short": true},
                  {"title": "Version", "value": "${BUILD_VERSION}", "short": true}
                ]
              }]
            }
      onFailure:
        - url: "${SLACK_WEBHOOK_URL}"
          payload: |
            {
              "text": "❌ Twenty CRM deployment failed",
              "attachments": [{
                "color": "danger",
                "fields": [
                  {"title": "Service", "value": "twenty-crm", "short": true},
                  {"title": "Error", "value": "${ERROR_MESSAGE}", "short": false}
                ]
              }]
            }

  # ==========================================================================
  # MONITORING
  # ==========================================================================
  monitoring:
    prometheus:
      enabled: true
      path: /metrics
      port: 3000

    customMetrics:
      - name: twenty_contacts_total
        type: gauge
        description: "Total contacts in CRM"
      - name: twenty_companies_total
        type: gauge
        description: "Total companies in CRM"
      - name: twenty_deals_total
        type: gauge
        description: "Total deals by stage"
        labels: ["stage"]
      - name: twenty_activities_total
        type: counter
        description: "Total activities logged"
        labels: ["type"]
      - name: twenty_webhook_received_total
        type: counter
        description: "Webhooks received from MADFAM sites"
        labels: ["source", "event"]

    alerts:
      - name: TwentyCRMHighErrorRate
        condition: rate(http_requests_total{service="twenty-crm",status=~"5.."}[5m]) / rate(http_requests_total{service="twenty-crm"}[5m]) > 0.05
        duration: 5m
        severity: warning
        annotations:
          summary: "High error rate on Twenty CRM"
          description: "Error rate is above 5% for 5 minutes"

      - name: TwentyCRMDatabaseSlowQueries
        condition: histogram_quantile(0.99, rate(pg_query_duration_seconds_bucket{service="twenty-crm"}[5m])) > 2
        duration: 5m
        severity: warning
        annotations:
          summary: "Slow database queries"
          description: "99th percentile query time is above 2 seconds"

      - name: TwentyCRMLowAvailability
        condition: up{service="twenty-crm"} < 1
        duration: 2m
        severity: critical
        annotations:
          summary: "Twenty CRM unavailable"
          description: "No healthy Twenty CRM instances"

  # ==========================================================================
  # MADFAM INTEGRATION CONFIG
  # ==========================================================================
  integrations:
    # Webhook endpoints for lead capture
    webhooks:
      - name: madfam-lead-capture
        path: /api/webhooks/madfam/leads
        methods: ["POST"]
        authentication:
          type: hmac
          header: X-Webhook-Signature
          secretRef:
            name: twenty-crm-secrets
            key: webhook-secret
        mapping:
          # Map madfam.io lead data to Twenty CRM contacts
          source: "madfam-site"
          targetObject: "person"
          fieldMapping:
            email: "$.email"
            firstName: "$.name.split(' ')[0]"
            lastName: "$.name.split(' ').slice(1).join(' ')"
            company: "$.company"
            phone: "$.phone"
            leadSource: "'madfam.io'"
            customFields:
              product_interest: "$.product"
              lead_score: "$.score"
              use_case: "$.useCase"
              team_size: "$.teamSize"

      - name: aureo-demo-request
        path: /api/webhooks/aureo/demos
        methods: ["POST"]
        authentication:
          type: hmac
          header: X-Webhook-Signature
          secretRef:
            name: twenty-crm-secrets
            key: webhook-secret
        mapping:
          source: "aureo-labs"
          targetObject: "opportunity"
          fieldMapping:
            name: "$.product + ' Demo Request - ' + $.company"
            company: "$.company"
            stage: "'Demo Requested'"
            amount: "$.estimatedValue"
            customFields:
              demo_product: "$.product"
              demo_date: "$.preferredDate"
              contact_email: "$.email"

    # SSO with Janua
    sso:
      provider: janua
      config:
        autoCreateUsers: true
        defaultRole: "member"
        attributeMapping:
          email: "email"
          name: "name"
          picture: "picture"
        groupMapping:
          "madfam-admins": "admin"
          "madfam-sales": "member"

  # ==========================================================================
  # COMPLIANCE
  # ==========================================================================
  compliance:
    requirements:
      - id: CRM-001
        description: "All customer data must be encrypted at rest"
        status: implemented
      - id: CRM-002
        description: "Access logs must be retained for 90 days"
        status: implemented
      - id: CRM-003
        description: "SSO must be enforced for all users"
        status: implemented
      - id: CRM-004
        description: "Data export must be available for GDPR requests"
        status: implemented

    audit:
      enabled: true
      events:
        - contact_created
        - contact_updated
        - contact_deleted
        - deal_created
        - deal_stage_changed
        - deal_closed
        - user_login
        - user_logout
        - data_export
        - webhook_received
