# Waybill - Cost Tracking and Budget Alerts
# Usage metrics collection and billing integration for Enclii

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: waybill
  project: enclii-platform
  description: Cost tracking, usage metrics, and billing integration

spec:
  # Build from the Enclii repository
  build:
    type: dockerfile
    dockerfile: apps/waybill/Dockerfile
    context: .
    target: api
    source:
      git:
        repository: https://github.com/madfam-org/enclii
        branch: main
        # Auto-deploy on push to main
        autoDeploy: true

  runtime:
    port: 8080
    replicas: 1
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

    # Health checks
    healthCheck: /health
    readinessProbe:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      path: /health
      initialDelaySeconds: 30
      periodSeconds: 10

  # Environment variables
  env:
    - name: PORT
      value: "8080"
    - name: LOG_LEVEL
      value: info

    # Database connection (shared PostgreSQL)
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: waybill-secrets
          key: DATABASE_URL

    # Stripe integration (optional)
    - name: STRIPE_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: waybill-secrets
          key: STRIPE_SECRET_KEY
          optional: true

    - name: STRIPE_WEBHOOK_SECRET
      valueFrom:
        secretKeyRef:
          name: waybill-secrets
          key: STRIPE_WEBHOOK_SECRET
          optional: true

    - name: STRIPE_PUBLISHABLE_KEY
      valueFrom:
        secretKeyRef:
          name: waybill-secrets
          key: STRIPE_PUBLISHABLE_KEY
          optional: true

    # Internal API authentication
    - name: INTERNAL_API_KEY
      valueFrom:
        secretKeyRef:
          name: waybill-secrets
          key: INTERNAL_API_KEY
          optional: true

  # Service-level objectives
  slo:
    availability: 99.5
    latencyP95: 500
    errorRate: 1.0
