# Core Services Application
# Deploys: switchyard-api, switchyard-ui, roundhouse, waybill
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-services
  namespace: argocd
  labels:
    app.kubernetes.io/name: core-services
    app.kubernetes.io/part-of: enclii
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/madfam-org/enclii.git
    targetRevision: main
    path: infra/k8s/production
    # Kustomize configuration
    kustomize:
      # Allow image tag overrides via ArgoCD Image Updater
      images: []

  destination:
    server: https://kubernetes.default.svc
    namespace: enclii

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Better for CRDs

  # Ignore certain fields that change frequently
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Allow HPA to manage replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP  # Auto-assigned by K8s
