# External Secrets Operator Application
# Deploys: ESO for centralized secrets management (via Helm)
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: enclii
    app.kubernetes.io/component: secrets-management
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.9.11  # Pin to specific version
    helm:
      values: |
        # External Secrets Operator configuration for Enclii

        # Install CRDs
        installCRDs: true

        # Replica count
        replicaCount: 2

        # Resource limits
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 128Mi
            cpu: 50m

        # Webhook configuration
        webhook:
          replicaCount: 2
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 25m

        # Cert controller
        certController:
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
            requests:
              memory: 64Mi
              cpu: 25m

        # ServiceMonitor for Prometheus
        serviceMonitor:
          enabled: true
          namespace: monitoring

        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        # Tolerate GPU nodes (don't schedule on them)
        tolerations:
          - key: "nvidia.com/gpu"
            operator: "Exists"
            effect: "NoSchedule"

        # Anti-affinity for HA
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: external-secrets
                  topologyKey: kubernetes.io/hostname

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

  # Ignore status fields
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
---
# External Secrets Configuration
# Deploys: ClusterSecretStore and example ExternalSecrets
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets-config
    app.kubernetes.io/part-of: enclii
    app.kubernetes.io/component: secrets-management
  annotations:
    # Deploy after ESO is installed
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/madfam-org/enclii.git
    targetRevision: main
    path: infra/k8s/base/external-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

  # Ignore secrets (contain sensitive data)
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
        - /stringData
