# ArgoCD Image Updater Application
# Deploys: Image Updater for automated container image updates (via Helm)
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: enclii
    app.kubernetes.io/component: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-image-updater
    targetRevision: 0.9.6  # Pin to specific version
    helm:
      values: |
        # ArgoCD Image Updater configuration for Enclii

        # Logging configuration
        config:
          logLevel: info

          # Registries configuration
          registries:
            - name: ghcr
              api_url: https://ghcr.io
              prefix: ghcr.io
              credentials: pullsecret:argocd/ghcr-credentials
              default: true
            - name: dockerhub
              api_url: https://registry-1.docker.io
              prefix: docker.io
            - name: gcr
              api_url: https://gcr.io
              prefix: gcr.io

          # Git configuration for write-back
          git:
            email: argocd-image-updater@enclii.dev
            name: ArgoCD Image Updater

        # Resource limits
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 128Mi
            cpu: 50m

        # ServiceMonitor disabled - requires Prometheus Operator
        metrics:
          enabled: true
          serviceMonitor:
            enabled: false

        # Pod disruption budget
        podDisruptionBudget:
          enabled: true
          minAvailable: 1

        # Replica count
        replicaCount: 1

        # Tolerate GPU nodes (don't schedule on them)
        tolerations:
          - key: "nvidia.com/gpu"
            operator: "Exists"
            effect: "NoSchedule"

        # Additional environment variables
        extraEnv:
          - name: ARGOCD_GRPC_WEB
            value: "true"
          - name: ARGOCD_SERVER
            value: "argocd-server.argocd.svc.cluster.local"
          - name: ARGOCD_INSECURE
            value: "true"

        # Mount git credentials for write-back
        authScripts:
          enabled: true
          scripts:
            git-creds.sh: |
              #!/bin/sh
              cat /app/config/git-credentials

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

  # Ignore status fields
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
---
# Image Updater Configuration
# Deploys: Registry and Git credentials configuration
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: image-updater-config
    app.kubernetes.io/part-of: enclii
    app.kubernetes.io/component: gitops
  annotations:
    # Deploy after image updater
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/madfam-org/enclii.git
    targetRevision: main
    path: infra/argocd-image-updater

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true

  # Ignore secrets (contain sensitive data)
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
        - /stringData
