---
# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: enclii
type: Opaque
stringData:
  username: postgres
  password: password
  database: enclii_dev
  database-url: "postgres://postgres:password@postgres:5432/enclii_dev?sslmode=disable"

---
# Redis Secret
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: enclii-system
type: Opaque
data:
  # Redis is configured without password for development
  password: ""

---
# JWT Secret for token signing
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  labels:
    app.kubernetes.io/name: switchyard-api
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/part-of: enclii
type: Opaque
stringData:
  jwt-secret: "dev-jwt-secret-key-change-in-production-use-rsa-keys"
  jwt-issuer: "enclii-dev"
  private-key: |
    -----BEGIN RSA PRIVATE KEY-----
    # Development only - use proper RSA keys in production
    -----END RSA PRIVATE KEY-----
  public-key: |
    -----BEGIN RSA PUBLIC KEY-----  
    # Development only - use proper RSA keys in production
    -----END RSA PUBLIC KEY-----

---
# Container Registry Secret
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: enclii-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ2l0aHViLXRva2VuIiwicGFzc3dvcmQiOiJnaXRodWJfcGF0X3Rva2VuIn19fQ==

---
# Application Configuration Secret
apiVersion: v1
kind: Secret
metadata:
  name: switchyard-secret
  namespace: enclii-system
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBwb3N0Z3JlczozNjMzL2VuY2xpaV9kZXY/c3NsbW9kZT1kaXNhYmxl  # Full DB URL
  redis-url: cmVkaXM6Ly9yZWRpczozNjQ2  # redis://redis:6379
  oidc-client-secret: ZW5jbGlpLXNlY3JldA==  # enclii-secret
  registry-url: Z2hjci5pby9tYWRmYW0=  # ghcr.io/madfam
  build-cache-dir: L3RtcC9lbmNsaWktY2FjaGU=  # /tmp/enclii-cache

---
# TLS Certificate Secret (for HTTPS)
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: enclii-system
type: kubernetes.io/tls
data:
  # Self-signed certificate for development
  # In production, use cert-manager or proper CA-issued certificates
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded private key