---
# PostgreSQL Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: enclii-system
type: Opaque
data:
  # Base64 encoded values - these would be properly generated in production
  username: cG9zdGdyZXM=  # postgres
  password: cGFzc3dvcmQ=  # password
  database: ZW5jbGlpX2Rldig=  # enclii_dev

---
# Redis Secret
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: enclii-system
type: Opaque
data:
  # Redis is configured without password for development
  password: ""

---
# JWT Secret for token signing
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: enclii-system
type: Opaque
data:
  # This should be a secure random key in production
  private-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ==  # Base64 encoded RSA private key
  public-key: LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0t    # Base64 encoded RSA public key

---
# Container Registry Secret
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: enclii-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZ2l0aHViLXRva2VuIiwicGFzc3dvcmQiOiJnaXRodWJfcGF0X3Rva2VuIn19fQ==

---
# Application Configuration Secret
apiVersion: v1
kind: Secret
metadata:
  name: switchyard-secret
  namespace: enclii-system
type: Opaque
data:
  database-url: cG9zdGdyZXM6Ly9wb3N0Z3JlczpwYXNzd29yZEBwb3N0Z3JlczozNjMzL2VuY2xpaV9kZXY/c3NsbW9kZT1kaXNhYmxl  # Full DB URL
  redis-url: cmVkaXM6Ly9yZWRpczozNjQ2  # redis://redis:6379
  oidc-client-secret: ZW5jbGlpLXNlY3JldA==  # enclii-secret
  registry-url: Z2hjci5pby9tYWRmYW0=  # ghcr.io/madfam
  build-cache-dir: L3RtcC9lbmNsaWktY2FjaGU=  # /tmp/enclii-cache

---
# TLS Certificate Secret (for HTTPS)
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: enclii-system
type: kubernetes.io/tls
data:
  # Self-signed certificate for development
  # In production, use cert-manager or proper CA-issued certificates
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # Base64 encoded private key