version: "2"

run:
  timeout: 5m
  go: "1.24"
  tests: false  # Skip linting test files (many false positives)

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
  settings:
    errcheck:
      # Don't check error returns for common Close() methods
      # These are typically deferred and errors are logged but not returned
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.Response).Body.Close
        - io.ReadCloser.Close

issues:
  # Exclude staticcheck style suggestions (QF* rules) - these are suggestions, not errors
  exclude-rules:
    - linters:
        - staticcheck
      text: "^QF"

  # Limit issues to avoid overwhelming output - will still catch new problems
  max-issues-per-linter: 20
  max-same-issues: 5
