# ArgoCD Repository Credentials for OCI/Helm Charts
#
# This file configures ArgoCD to authenticate with OCI registries
# (like ghcr.io) for pulling Helm charts.
#
# Usage:
#   1. Generate a GitHub PAT with `read:packages` scope
#   2. Base64 encode: echo -n "YOUR_PAT" | base64
#   3. Replace the placeholder below
#   4. kubectl apply -f infra/argocd/repo-credentials.yaml
#
# For ghcr.io public charts (like ARC), authentication is optional but
# recommended to avoid rate limiting.
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-oci-creds
  namespace: argocd
  labels:
    # ArgoCD recognizes this label for repository credentials
    argocd.argoproj.io/secret-type: repository
stringData:
  # OCI registry URL (must match the repoURL in Application specs)
  url: ghcr.io
  # Registry type
  type: helm
  # Enable OCI support
  enableOCI: "true"
  # GitHub username (any valid username works for PAT auth)
  username: madfam-org
  # GitHub Personal Access Token with read:packages scope
  # Generate at: https://github.com/settings/tokens/new?scopes=read:packages
  # DO NOT commit real tokens - use sealed secrets or external secrets operator
  password: "${GITHUB_TOKEN}"
---
# Alternative: Credential template for all ghcr.io OCI repos
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-oci-creds-template
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  # Pattern matches all ghcr.io OCI URLs
  url: https://ghcr.io
  type: helm
  enableOCI: "true"
  username: madfam-org
  password: "${GITHUB_TOKEN}"
---
# Git repository credentials for private repos
apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  # Pattern matches all github.com URLs
  url: https://github.com/madfam-org
  type: git
  username: madfam-org
  # Same PAT works for git repos (needs repo scope for private repos)
  password: "${GITHUB_TOKEN}"
